### ISSUE TITLE
Amazon Managed Apache Cassandra Service / Keyspaces

### ISSUE THREAD

**Issue by markvdlaan93** [hashicorp/terraform-provider-aws#11221]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since one week, AWS released Managed Apache Cassandra service in a couple of regions: https://aws.amazon.com/mcs/. Obviously, I can't find anything in the Terraform docs, so I'm assuming that this still needs to be implemented. If this is the case, I would like to contribute. Please have a look at the potential Terraform configuration below.

### New or Affected Resource(s)

I'm not sure which existing resources are affected by this but new resources could be named:
* aws_mcs_keyspace
* aws_mcs_table

### Potential Terraform Configuration

```hcl
"aws_mcs_keyspace" "example" {
     name = "mcs-keyspace-example"
     exists = "true"
     region = "eu-north-1"
     replication {
         class = "SingleRegionStrategy"
     }
}

"aws_mcs_table" "example" {
   name = "mcs-table-example"
   keyspace_arn = "${aws_mcs_keyspace.example.arn}"
   exists = "true"
   fields {
       columns {
            name = "name",
            type = "text",
       }
       columns {
            name = "email",
            type = "text",
       }
   }
   primary_key = ["email", "name"]
   # clustering key?
}
```

### References

* https://aws.amazon.com/blogs/aws/new-amazon-managed-apache-cassandra-service-mcs/
* https://aws.amazon.com/mcs/pricing/

**Comment by bflad** [comment]
Hi @markvdlaan93 👋 Thank you for submitting this.

At this current time, AWS has not released an API or SDK for this new service:
* https://docs.aws.amazon.com/mcs/latest/devguide/what-is-mcs.html
* https://docs.aws.amazon.com/sdk-for-go/api/

Without these, we cannot implement support for this AWS service in Terraform. Please reach out to AWS Support or your account managers to ask about API support.

**Comment by ansha1** [comment]
Hi Everyone !
I am also looking for terraform documentation for setting up mcs. Please let us know if we have any
Thanks,
Anurag

**Comment by ewbankkit** [comment]
Amazon Keyspaces (for Apache Cassandra) is now generally available:

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2020/04/amazon-keyspaces-for-apache-cassandra-is-now-generally-available/)
* [Blog post](https://aws.amazon.com/blogs/aws/new-amazon-keyspaces-for-apache-cassandra-is-now-generally-available/)

No support in the AWS API yet though.

**Comment by kvaidas** [comment]
It appears some sort of integration with an IAM user might be necessary since that's where one would create a Cassandra credential that's used by clients to connect.

**Comment by codingconcepts** [comment]
Hey all,

I was battling with this today and wanted to share my solution in case it's helpful for anyone else. I ended up using CloudFormation _via_ Terraform as follows to create a keyspace and a table:

**main.tf**
``` hcl
provider "aws" {
  region = "eu-central-1"
  version = "~> 3.0"
}

resource "aws_cloudformation_stack" "keyspaces" {
  name = "my-keyspace"

  template_body = file("./keyspace.yaml")
}
```

**keyspace.yaml**
``` yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyKeyspace:
    Type: AWS::Cassandra::Keyspace
    Properties:
      KeyspaceName: abc
  
  MyTable:
    Type: AWS::Cassandra::Table
    DependsOn: MyKeyspace
    Properties:
      KeyspaceName: abc
      TableName: my_table
      PartitionKeyColumns:
        - ColumnName: id
          ColumnType: TEXT
      BillingMode:
        Mode: ON_DEMAND
```
