### ISSUE TITLE
awsproviderlint: New Check: Prefer tfawserr helpers over directly checking (*awserr.Error).Code()

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#12986]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Terraform AWS Provider has helper functions for working with the AWS Go SDK awserr package Error type: `tfawserr.ErrCodeEquals(error, string)`, `tfawserr.ErrMessageContains(error, string, string)`

We prefer these helper functions for a few reasons:

- Simplifies and standardizes AWS Go SDK error checking logic
- Performs Go 1.13 wrapped error checking (when additional context is added via fmt.Errorf() and the %w verb)

### Flagged Code

```go
if awsErr, ok := err.(awserr.Error); ok && awsErr.Code() == "NoSuchBucketPolicy" {
}
```

### Passing Code

```go
import "github.com/hashicorp/aws-sdk-go-base/tfawserr"
// ...
if tfawserr.ErrCodeEquals(err, "NoSuchBucketPolicy") {
}
```

**Comment by bflad** [comment]
Given this is a little easier to implement in `semgrep` rather than direct AST, this `semgrep` rule should get us close:

```
  - id: aws-go-sdk-error-code-helper
    languages: [go]
    message: 'Use `isAWSErr()` helper for checking AWS Go SDK errors (e.g. `isAWSErr(err, CODE, MESSAGE)`)'
    paths:
      exclude:
        - vendor/
      include:
        - aws/
    patterns:
      - pattern-either:
        - pattern: if $AWSERR, $OK := $ORIGINALERR.(awserr.Error); $OK && $AWSERR.Code() == $CODE { $BODY }
        - pattern: |
            if $AWSERR, $OK := $ORIGINALERR.(awserr.Error); $OK {
              if $AWSERR.Code() == $CODE { $BODY }
            }
    severity: WARNING
```

Unfortunately `semgrep`'s `fix` handling in Go is a little lacking at the moment and `$BODY` drops important syntax tokens, but at least we can report it.
