### ISSUE TITLE
awsproviderlint: New Check: Prefer (*awserr.Error) instead of (*awserr.Error).Code() / (*awserr.Error).Message() in fmt.Errorf()

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#12987]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS Go SDK provides a good String() implementation of errors including the ErrorCode, ErrorMessage, and request ID for troubleshooting with AWS Support. We should avoid trimming out useful bits from these error messages by referencing Code(), Message(), etc. and instead simplify to just referencing the error object itself.

### Flagged Code

```
fmt.Errorf("AWS error oh no: %s", err.Code())
fmt.Errorf("AWS error oh no: %s: %s", err.Code(), err.Message())
```
### Passing Code
```
fmt.Errorf("AWS error oh no: %w", err)
```

**Comment by bflad** [comment]
Inexact (would need to do type checking with `go/analysis`) but covers this case well, a potential `semgrep` rule:

```yaml
  - id: fmt-Errorf-awserr-Error-Code
    languages: [go]
    message: Prefer `err` with `%w` format verb instead of `err.Code()` or `err.Message()`
    paths:
      exclude:
        - vendor/
      include:
        - aws/
    patterns:
      - pattern-either:
        - pattern: fmt.Errorf(..., $ERR.Code(), ...)
        - pattern: fmt.Errorf(..., $ERR.Message(), ...)
    severity: WARNING
```
