### ISSUE TITLE
Prefer AWS Go SDK pointer conversion functions instead of raw * dereferencing

### ISSUE THREAD

**Issue by breathingdust** [hashicorp/terraform-provider-aws#12992]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS Go SDK provides a large amount of type conversion functions for going from pointer values to underlying values and vice-versa. They automatically handle nil values by substituting the zero-value for a type (e.g. aws.StringValue(*string) will convert a nil *string to "").

We prefer using these functions to:

- Simplify SDK object access
- Prevent potential panics (many times, nil checking is not performed at all before * dereferencing)

There are still cases where nil checking is preferred due to behaviors we want in Terraform, however even in these cases we should prefer the AWS Go SDK conversion functions for consistency.

### Flagged Code
```
value := *output.Value
```
### Passing Code
```
value := aws.StringValue(output.Value)
```
### References

- https://docs.aws.amazon.com/sdk-for-go/api/aws/

**Comment by bflad** [comment]
Covering `semgrep` rule for #16532:

```yaml
  - id: prefer-aws-go-sdk-pointer-conversion-conditional
    languages: [go]
    message: Prefer AWS Go SDK pointer conversion functions for dereferencing during conditionals, e.g. aws.StringValue()
    paths:
      exclude:
        - awsproviderlint/vendor/
      include:
        - aws/
    patterns:
      - pattern-either:
        - pattern: '$LHS == *$RHS'
        - pattern: '*$LHS == $RHS'
    severity: WARNING
```

```
aws/resource_aws_lambda_function.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-conditional: Prefer AWS Go SDK pointer conversion functions for dereferencing during conditionals, e.g. aws.StringValue()
817:	if *function.PackageType == lambda.PackageTypeZip {
```

Other covering rules to enable:

```yaml
  - id: prefer-aws-go-sdk-pointer-conversion-assignment
    languages: [go]
    message: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
    paths:
      exclude:
        - aws/internal/generators/
        - aws/internal/keyvaluetags/
        - awsproviderlint/vendor/
      include:
        - aws/
    patterns:
      - pattern: '$LHS = *$RHS'
      - pattern-not: '*$LHS2 = *$RHS'
    severity: WARNING
```

e.g.

```
aws/resource_aws_vpc.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
308:					classiclink_enabled = *v.ClassicLinkEnabled
333:					classiclinkdns_enabled = *v.ClassicLinkDnsSupported

aws/resource_aws_waf_sql_injection_match_set.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
179:		m["text_transformation"] = *t.TextTransformation

aws/resource_aws_waf_web_acl.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
239:	arn := *resp.WebACL.WebACLArn
```

```yaml
  - id: prefer-aws-go-sdk-pointer-conversion-ResourceData-SetId
    languages: [go]
    message: Prefer AWS Go SDK pointer conversion aws.StringValue() function for dereferencing during d.SetId()
    paths:
      include:
        - aws/
    pattern: 'd.SetId(*$VALUE)'
    severity: WARNING
```

e.g.

```
aws/resource_aws_wafregional_web_acl.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-ResourceData-SetId: Prefer AWS Go SDK pointer conversion aws.StringValue() function for dereferencing during d.SetId()
197:	d.SetId(*resp.WebACL.WebACLId)

aws/resource_aws_workspaces_ip_group.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-ResourceData-SetId: Prefer AWS Go SDK pointer conversion aws.StringValue() function for dereferencing during d.SetId()
75:	d.SetId(*resp.GroupId)
```
