### ISSUE TITLE
403 InvalidClientTokenId: The security token included in the request is invalid (executing via GitHub Actions)

### ISSUE THREAD

**Issue by vkoukoutsas** [hashicorp/terraform-provider-aws#14108]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform v0.12.28`

### Affected Resource(s)

* aws_provider v2.69.0
* sts.amazonaws.com
* aws-sdk-go/1.30.12 (go1.12.13; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.28

### Terraform Configuration Files

main.tf
```hcl
provider "aws" {
  region  = var.aws_region
  version = "~> 2.69.0"
}

terraform {
 backend "s3" {
   encrypt        = true
   bucket         = "random-name"
   profile        = "default"
   region         = "eu-west-1"
   key            = "path/to/tfstate/file"
   dynamodb_table = "bucket-lock"
 }
}
```

### Debug Output

https://gist.github.com/vkoukoutsas/aa452b0675c393aaa3c947ce8b6b1f62

### Expected Behavior

Existing configuration is run through GitHub Actions using terraform OSS v0.12.28 binary
`terraform init` should initialize the local configuration files with no issues.
Using a user's `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` and `AWS_ROLE_TO_ASSUME` the [Configure AWS Credentials](https://github.com/aws-actions/configure-aws-credentials) GitHub Action configures the credentials which are used successfully from terraform.

### Actual Behavior

[Configure AWS Credentials](https://github.com/aws-actions/configure-aws-credentials) GitHub Action configures the credentials successfully and generates a session token.
An error is returned when the aws_provider is trying to acquire the account_id after the `terraform init` command.

### Steps to Reproduce

1. `terraform init`

### Important Factoids

Terraform is installed and executed through GitHub Actions with the following configuration:
```yaml
name: Terraform Apply
on: [push]
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-west-1"
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600
          role-session-name: GitHubActions

      - name: Install Terraform
        env:
            TERRAFORM_VERSION: "0.12.28"
        run: |
          tf_version=$TERRAFORM_VERSION
          wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
          unzip terraform_"$tf_version"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          

      - name: Verify Terraform version
        run: terraform --version
    
      - name: Terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_LOG: TRACE
        run: terraform init
```

### References

* #0000

**Comment by jdrydn** [comment]
I'm seeing this error, unrelated to Terraform & assuming a role:

```
- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: eu-west-2
```

Could be the AWS region?
