### ISSUE TITLE
tests/provider: Ensure CheckDestroy functions continue rather than return nil

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#15847]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`CheckDestroy` functions contain a `for` loop to check all resource states. If a resource matches and is not found (good in this case), the logic should `continue` the loop instead of immediately `return nil`, otherwise if multiple resources exist they will not all be checked.

### Potential semgrep Implementation

```yaml
  - id: CheckDestroy-for-loop-return-nil
    languages: [go]
    message: CheckDestroy functions should use `continue` inside `for` loop instead of `return nil`
    paths:
      include:
        - "*_test.go"
    patterns:
      - pattern: |
          func $FUNC($STATE *terraform.State) error {
            ...
            for _, $RESOURCESTATE := range $STATE.RootModule().Resources {
              ...
              return nil
              ...
            }
            ...
          }
    severity: WARNING
```

Example report (where line 481 should be updated):

```
aws/resource_aws_acmpca_certificate_authority_test.go
severity:warning rule:CheckDestroy-for-loop-return-nil: CheckDestroy functions should use `continue` inside `for` loop instead of `return nil`
465:func testAccCheckAwsAcmpcaCertificateAuthorityDestroy(s *terraform.State) error {
466:	conn := testAccProvider.Meta().(*AWSClient).acmpcaconn
467:
468:	for _, rs := range s.RootModule().Resources {
469:		if rs.Type != "aws_acmpca_certificate_authority" {
470:			continue
471:		}
472:
473:		input := &acmpca.DescribeCertificateAuthorityInput{
474:			CertificateAuthorityArn: aws.String(rs.Primary.ID),
475:		}
476:
477:		output, err := conn.DescribeCertificateAuthority(input)
478:
479:		if err != nil {
480:			if isAWSErr(err, acmpca.ErrCodeResourceNotFoundException, "") {
481:				return nil
482:			}
483:			return err
484:		}
485:
486:		if output != nil && output.CertificateAuthority != nil && aws.StringValue(output.CertificateAuthority.Arn) == rs.Primary.ID && aws.StringValue(output.CertificateAuthority.Status) != acmpca.CertificateAuthorityStatusDeleted {
487:			return fmt.Errorf("ACMPCA Certificate Authority %q still exists in non-DELETED state: %s", rs.Primary.ID, aws.StringValue(output.CertificateAuthority.Status))
488:		}
489:	}
490:
491:	return nil
492:
493:}
```
