### ISSUE TITLE
provider: Remove extraneous AWS Go SDK value wrapping in d.Set()

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16554]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [`(*schema.ResourceData).Set()` receiver method](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ResourceData.Set) automatically handles pointer types and `nil` values, so wrapping the values with the AWS Go SDK pointer conversion functions, e.g. `aws.StringValue()` is extraneous.

Note: This should _not_ include slice/map functions calls such as `aws.StringValueSlice()` since those conversions are not automatic.

### Example semgrep Rule

```yaml
rules:
  - id: helper-schema-ResourceData-Set-extraneous-value-pointer-conversion
    languages: [go]
    message: AWS Go SDK pointer conversion function for `d.Set()` value is extraneous
    paths:
      include:
        - aws/
    patterns:
      - pattern-either:
        - pattern: d.Set($ATTRIBUTE, aws.BoolValue($APIOBJECT))
        - pattern: d.Set($ATTRIBUTE, aws.Int64Value($APIOBJECT))
        - pattern: d.Set($ATTRIBUTE, int(aws.Int64Value($APIOBJECT)))
        - pattern: d.Set($ATTRIBUTE, aws.StringValue($APIOBJECT))
    severity: WARNING
```

### Example Reports

```
aws/resource_aws_wafv2_rule_group.go
severity:warning rule:helper-schema-ResourceData-Set-extraneous-value-wrapping: AWS Go SDK value wrapping in `d.Set()` is extraneous
188:	d.Set("name", aws.StringValue(resp.RuleGroup.Name))
189:	d.Set("capacity", aws.Int64Value(resp.RuleGroup.Capacity))
190:	d.Set("description", aws.StringValue(resp.RuleGroup.Description))
191:	d.Set("arn", aws.StringValue(resp.RuleGroup.ARN))
192:	d.Set("lock_token", aws.StringValue(resp.LockToken))

aws/resource_aws_wafv2_web_acl.go
severity:warning rule:helper-schema-ResourceData-Set-extraneous-value-wrapping: AWS Go SDK value wrapping in `d.Set()` is extraneous
215:	d.Set("name", aws.StringValue(resp.WebACL.Name))
216:	d.Set("capacity", aws.Int64Value(resp.WebACL.Capacity))
217:	d.Set("description", aws.StringValue(resp.WebACL.Description))
218:	d.Set("arn", aws.StringValue(resp.WebACL.ARN))
219:	d.Set("lock_token", aws.StringValue(resp.LockToken))

aws/resource_aws_worklink_fleet.go
severity:warning rule:helper-schema-ResourceData-Set-extraneous-value-wrapping: AWS Go SDK value wrapping in `d.Set()` is extraneous
176:	d.Set("name", aws.StringValue(resp.FleetName))
177:	d.Set("display_name", aws.StringValue(resp.DisplayName))
178:	d.Set("optimize_for_end_user_location", aws.BoolValue(resp.OptimizeForEndUserLocation))
179:	d.Set("company_code", aws.StringValue(resp.CompanyCode))
```

### Affected Resources

TBD

### Definition of Done

* Rule added to `.semgrep.yml` with no reports on main branch and CI passes
