### ISSUE TITLE
Fix and Enable go-mnd Linter for resource.Retry and resource.RetryContext Arguments

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16753]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

_NOTE: This requires upstream `golangci-lint` implementation work and release first._

The [`go-mnd` analyzer](https://github.com/tommy-muehle/go-mnd) is a magic number detector for Go. It currently is supported in [`golangci-lint`](https://golangci-lint.run/), however we do not enable it because it currently would have many false positives for our codebase. These false positives stem from schema validation and other cases where the magic numbers are determined by the AWS APIs, but not modeled as a constant we can reference in the AWS Go SDK, e.g.

```
aws/data_source_aws_codeartifact_authorization_token.go:33:28: mnd: Magic number: 900, in <argument> detected (gomnd)
					validation.IntBetween(900, 43200),
					                      ^
```

In particular though, one needed use case for `go-mnd` reports is usage of `resource.Retry()` and `resource.RetryContext()` calls where the `time.Duration` is a magic number. Many resources use this type of logic to handle eventual consistency issues in the API, however keeping them properly in sync is hard without a single constant to reference.

In the future, we can determine how useful (and painful) it might be to enable `go-mnd` on other functions or detection types (such as assignment).

### Affected Resources

This will be updated when appropriate.

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/16752

**Comment by bflad** [comment]
Once https://github.com/golangci/golangci-lint/issues/1557 is resolved, released, and the dependency is updated here, this configuration should get us close:

```yaml
linters-settings:
  gomnd:
    settings:
      mnd:
        checks:
          - argument
        ignored-functions:
          - aws.Int64
          - schema.DefaultTimeout
          - validation.FloatBetween
          - validation.IntAtLeast
          - validation.IntBetween
          - validation.StringLenBetween
```
