### ISSUE TITLE
Implement d.IsNewResource() Checks In Resource Read Functions

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#16796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

During resource creation, Terraform CLI expects either a properly applied state for the new resource or an error. To signal proper resource existence, the Terraform Plugin SDK uses an underlying resource identifier (set via `d.SetId(/* some value */)`). If for some reason the resource creation is returned without an error, but also without the resource identifier being set, Terraform CLI will return an error such as:

```
Error: Provider produced inconsistent result after apply

When applying changes to aws_sns_topic_subscription.sqs,
provider "registry.terraform.io/hashicorp/aws" produced an unexpected new
value: Root resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

A typical pattern in resource implementations in the `Create`/`CreateContext` function is to `return` the `Read`/`ReadContext` function at the end to fill in the Terraform State for all attributes. Another typical pattern in resource implementations in the `Read`/`ReadContext` function is to remove the resource from the Terraform State if the remote system returns an error or status that indicates the remote resource no longer exists by explicitly calling `d.SetId("")` and returning no error. If the remote system is not strongly read-after-write consistent (eventually consistent), this means the resource creation can return no error and also return no resource state.

To prevent this type of Terraform CLI error, the resource implementation should also check against `d.IsNewResource()` before removing from the Terraform State and returning no error. If that check is `true`, then remote operation error (or one synthesized from the non-existent status) should be returned instead. While adding this check will not fix the resource implementation to handle the eventually consistent nature of the remote system, the error being returned will be less opaque for operators and code maintainers to troubleshoot.

In the Terraform AWS Provider, an initial fix for the Terraform CLI error will typically look like:

```go
func resourceServiceThingCreate(d *schema.ResourceData, meta interface{}) error {
    /* ... */

    return resourceServiceThingRead(d, meta)
}

func resourceServiceThingRead(d *schema.ResourceData, meta interface{}) error {
    /* ... */

    output, err := conn.DescribeServiceThing(input)

    if !d.IsNewResource() && tfawserr.ErrCodeEquals(err, "ResourceNotFoundException") {
        log.Printf("[WARN] {Service} {Thing} (%s) not found, removing from state", d.Id())
        d.SetId("")
        return nil
    }

    if err != nil {
        return fmt.Errorf("error reading {Service} {Thing} (%s): %w", d.Id(), err)
    }

    /* ... */
}
```

The [Resource Lifecycle Retries](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md#resource-lifecycle-retries) documentation in the Contributing Guide also shows how to mitigate eventual consistency issues by retrying the remote operation for a short period of time.

To catch existing occurrences of this code problem and prevent it going forward, a `semgrep` rule will be added, e.g.

```yaml
  - id: helper-schema-ResourceData-SetId-empty-without-IsNewResource-check
    languages: [go]
    message: Calling `d.SetId("")` should ensure `!d.IsNewResource()` is checked first
    paths:
      include:
        - aws/resource*.go
    patterns:
      - pattern-either:
        - pattern: |
            d.SetId("")
            ...
            return nil
      - pattern-not-inside: |
          if ... {
            if <... d.IsNewResource() ...> { ... }
            ...
            d.SetId("")
            ...
            return nil
          }
      - pattern-not-inside: |
          if <... d.IsNewResource() ...> { ... }
    severity: WARNING
```

### Affected Resource(s)

https://gist.github.com/bflad/2c7a8df73a1e5e42d8d82af847f9f226

### References

- https://github.com/hashicorp/terraform-provider-aws/issues/9725
- https://github.com/hashicorp/terraform-provider-aws/issues/9914
- https://github.com/hashicorp/terraform-provider-aws/issues/9987
- https://github.com/hashicorp/terraform-provider-aws/issues/10225
- https://github.com/hashicorp/terraform-provider-aws/issues/10587
- https://github.com/hashicorp/terraform-provider-aws/issues/11064
- https://github.com/hashicorp/terraform-provider-aws/issues/11737
- https://github.com/hashicorp/terraform-provider-aws/issues/11769
- https://github.com/hashicorp/terraform-provider-aws/issues/12127
- https://github.com/hashicorp/terraform-provider-aws/issues/12449
- https://github.com/hashicorp/terraform-provider-aws/issues/12679
- https://github.com/hashicorp/terraform-provider-aws/issues/12692
- https://github.com/hashicorp/terraform-provider-aws/issues/12829
- https://github.com/hashicorp/terraform-provider-aws/issues/12847
- https://github.com/hashicorp/terraform-provider-aws/issues/14043
- https://github.com/hashicorp/terraform-provider-aws/issues/15084
- https://github.com/hashicorp/terraform-provider-aws/issues/16142
- https://github.com/hashicorp/terraform-provider-aws/issues/16201
- https://github.com/hashicorp/terraform-provider-aws/issues/16247
- https://github.com/hashicorp/terraform-provider-aws/issues/16482
- https://github.com/hashicorp/terraform-provider-aws/issues/16695
- https://github.com/hashicorp/terraform-provider-aws/issues/17139
- https://github.com/hashicorp/terraform-provider-aws/issues/17809
- https://github.com/hashicorp/terraform-provider-aws/issues/18103
- https://github.com/hashicorp/terraform-provider-aws/issues/18151
