### ISSUE TITLE
Tech-debt: Linter for using expandStringSet in favor of expandStringList of Sets

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#17057]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* use a tool like semgrep to catch these extraneous expansions i.e. Set -> List  -> expandStringList

### New or Affected Resource(s)

* quite a few 😆 

### Possible implementaton

```yml
  - id: example
    languages: [go]
    message: Prefer `expandStringSet()` function for converting a Set to a list of string pointers
    paths:
      include:
        - aws/
    pattern: expandStringList($RAWSET.List())
    severity: WARNING
```

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/17052
