### ISSUE TITLE
Add support for KMS key to aws_config_delivery_channel

### ISSUE THREAD

**Issue by parente** [hashicorp/terraform-provider-aws#17898]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Configuring AWS Config to deliver to a S3 bucket with KMS encryption is not currently supported by this provider.

```
Error: Creating Delivery Channel failed: InsufficientDeliveryPolicyException: Insufficient delivery policy to s3 bucket: arn:aws:s3:::test-config-findings, unable to write to bucket, provided s3 key prefix is 'test-sandbox', provided kms key is 'null'.

  on test-sandbox.tf line 100, in resource "aws_config_delivery_channel" "test_sandbox_aws_config":
 100: resource "aws_config_delivery_channel" "test_sandbox_aws_config" {
```

### New or Affected Resource(s)

* `aws_config_delivery_channel`

### Potential Terraform Configuration

```hcl
resource "aws_config_delivery_channel" "foo" {
  name                   = "example"
  s3_bucket_name = aws_s3_bucket.b.bucket
  kms_key_id          = aws_kms_key.some_key.arn
  depends_on        = [aws_config_configuration_recorder.foo]
}
```

### References

N/A

**Comment by alexnelsone** [comment]
Just ran into this issue. Tried running without KMS option.  Coded the following:

```
config_delivery_channel = config.CfnDeliveryChannel(self, 'ConfigDeliveryChannel',
                                                    name=f'{unique_id}-config-delivery-channel',
                                                    s3_bucket_name=config_bucket.bucket_arn,
                                                    sns_topic_arn=config_sns_topic.topic_arn,
                                                    s3_key_prefix=f'config',
                                                    config_snapshot_delivery_properties=
                                                        config.CfnDeliveryChannel.ConfigSnapshotDeliveryPropertiesProperty(
                                                            delivery_frequency='Three_Hours',
                                                        )
                                                    ).add_depends_on(bucket_policy)
```

which outputs:

```
ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      S3BucketName:
        Fn::GetAtt:
          - ConfigBucketA3490E76
          - Arn
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: Three_Hours
      Name: config-delivery-channel
      SnsTopicARN:
        Ref: SnsTopic7F0014F7
    DependsOn:
      - ConfigBucketPolicy
```

Running just a regular Cfn template that includes the following, works just fine.

```
  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    DependsOn:
      - ConfigBucketPolicy
    Properties:
      Name: config-delivery-channel
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: Three_Hours
      S3BucketName: !Ref ConfigBucket
      SnsTopicARN: !GetAtt SnsTopic.Arn
```
