### ISSUE TITLE
Add Linter for AWS Go SDK Set Method Usage

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-provider-aws#17905]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In addition to directly setting Go struct types fields associated with AWS Go SDK types:

```go
input.AttributeName = aws.String("example")
```

Version 1 of the AWS Go SDK generates `Set...()` methods, e.g.

```go
// SetAttributeName sets the AttributeName field's value.
func (s *Structure ) SetAttributeName(v string) *Structure {
	s.AttributeName = &v
	return s
}
```

The overwhelming style of this codebase is to directly set struct fields. Additionally, version 2 of the AWS Go SDK does not include these `Set...()` methods.

### Potential Semgrep Rule

```yaml
  - id: aws-go-sdk-field-assignment
    languages: [go]
    message: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
    paths:
      exclude:
        - aws/internal/generators/
        - awsproviderlint/vendor/
      include:
        - aws/
    patterns:
      - pattern: $TYPE.$SETFIELDFUNC($VALUE)
      - metavariable-regex:
          metavariable: "$SETFIELDFUNC"
          regex: "^Set[a-zA-Z]+"
      - pattern-not: 'conn.$SETFIELDFUNC($VALUE)'
      - pattern-not: 'd.SetConnInfo($VALUE)'
      - pattern-not: 'd.SetId($VALUE)'
      - pattern-not: 'd.SetNewComputed($VALUE)'
      - pattern-not: 'diff.SetNewComputed($VALUE)'
      - pattern-not: 'elbconn.$SETFIELDFUNC($VALUE)'
      - pattern-not: 'snsconn.$SETFIELDFUNC($VALUE)'
      - pattern-not: 'sqsconn.$SETFIELDFUNC($VALUE)'
    severity: WARNING
```

Current reports:

```
aws/elasticsearch_domain_structure.go
severity:warning rule:aws-go-sdk-field-assignment: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
38:					config.SetMasterUserOptions(&muo)

aws/resource_aws_ec2_traffic_mirror_filter_rule.go
severity:warning rule:aws-go-sdk-field-assignment: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
308:		input.SetRemoveFields(removeFields)

aws/resource_aws_ec2_traffic_mirror_session.go
severity:warning rule:aws-go-sdk-field-assignment: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
159:		input.SetRemoveFields(removeFields)

aws/resource_aws_kms_grant.go
severity:warning rule:aws-go-sdk-field-assignment: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
440:			constraint.SetEncryptionContextEquals(stringMapToPointers(contextEq.(map[string]interface{})))
--------------------------------------------------------------------------------
443:			constraint.SetEncryptionContextSubset(stringMapToPointers(contextSub.(map[string]interface{})))

aws/resource_aws_lambda_event_source_mapping.go
severity:warning rule:aws-go-sdk-field-assignment: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
238:		params.SetDestinationConfig(expandLambdaEventSourceMappingDestinationConfig(vDest.([]interface{})))
--------------------------------------------------------------------------------
389:			params.SetParallelizationFactor(int64(parallelizationFactor.(int)))
--------------------------------------------------------------------------------
393:			params.SetMaximumRetryAttempts(int64(maximumRetryAttempts.(int)))
--------------------------------------------------------------------------------
399:			params.SetBisectBatchOnFunctionError(bisectBatchOnFunctionError.(bool))
--------------------------------------------------------------------------------
403:			params.SetDestinationConfig(expandLambdaEventSourceMappingDestinationConfig(vDest.([]interface{})))

aws/resource_aws_neptune_cluster.go
severity:warning rule:aws-go-sdk-field-assignment: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
570:			logs.SetDisableLogTypes(expandStringSet(disableLogTypes))
--------------------------------------------------------------------------------
576:			logs.SetEnableLogTypes(expandStringSet(enableLogTypes))

aws/resource_aws_opsworks_permission.go
severity:warning rule:aws-go-sdk-field-assignment: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
124:		_, err := client.SetPermission(req)
--------------------------------------------------------------------------------
136:		_, err = client.SetPermission(req)

aws/resource_aws_s3_bucket.go
severity:warning rule:aws-go-sdk-field-assignment: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
1456:					ge.SetID(i)
--------------------------------------------------------------------------------
1459:					ge.SetType(t)
--------------------------------------------------------------------------------
1462:					ge.SetURI(u)
--------------------------------------------------------------------------------
2146:			lifecycleRuleAndOp.SetPrefix(r["prefix"].(string))
--------------------------------------------------------------------------------
2147:			lifecycleRuleAndOp.SetTags(tags)
--------------------------------------------------------------------------------
2148:			filter.SetAnd(lifecycleRuleAndOp)
--------------------------------------------------------------------------------
2150:			filter.SetPrefix(r["prefix"].(string))
--------------------------------------------------------------------------------
2152:		rule.SetFilter(filter)

aws/resource_aws_s3_object_copy.go
severity:warning rule:aws-go-sdk-field-assignment: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
628:		apiObject.SetEmailAddress(v)
--------------------------------------------------------------------------------
632:		apiObject.SetID(v)
--------------------------------------------------------------------------------
636:		apiObject.SetType(v)
--------------------------------------------------------------------------------
640:		apiObject.SetURI(v)

aws/resource_aws_ssm_parameter.go
severity:warning rule:aws-go-sdk-field-assignment: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
242:		paramInput.SetKeyId(keyID.(string))

aws/structure.go
severity:warning rule:aws-go-sdk-field-assignment: Prefer direct assignment to AWS Go SDK fields, e.g. input.Field = aws.String("example")
1612:				onFailure.SetDestination(mOnFailure["destination_arn"].(string))
--------------------------------------------------------------------------------
1616:	dest.SetOnFailure(onFailure)
ran 10 rules on 2135 files: 29 findings
```

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/17902
