### ISSUE TITLE
aws_lb data source fails to identify LB by tag

### ISSUE THREAD

**Issue by emilchitas** [hashicorp/terraform-provider-aws#20489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.53.0

### Affected Resource(s)

* aws_lb

### Kubernetes service configuration:
We have a LoadBalancer provisioned in AWS, which is created by the aws lb controller. The service is configured like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: lb_name=foo-bar-balancer
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: ingress
spec:
  <...>
status:
  loadBalancer:
    ingress:
      - hostname: <>.elb.us-east-1.amazonaws.com
```

### Terraform Configuration Files

```hcl
data "aws_route53_zone" "dns_zone" {
  name         = var.hosted_zone
  private_zone = false
}

data "aws_lb" "main" {
  tags = {
    lb_name = local.lb_name_tag
  }
  depends_on = [helm_release.ingress_gateway]
}

resource "aws_route53_record" "top_level" {
  zone_id = data.aws_route53_zone.dns_zone.zone_id
  name    = var.hosted_zone
  type    = "A"

  alias {
    name                   = data.aws_lb.main.dns_name
    zone_id                = data.aws_lb.main.zone_id
    evaluate_target_health = true
  }
}
```

### Expected Behavior

Terraform identifies the LoadBalancer based on the applied tag. 

### Actual Behavior

Terraform fails with the following error:
```
Error: Search returned 0 results, please revise so only one is returned
```
 even though 2 lines above, the LoadBalancer id appears in the log:
 ```
data.aws_lb.main: Reading... [id=arn:aws:elasticloadbalancing:us-east-1:494495723522:loadbalancer/net/################################/################]
data.aws_route53_zone.dns_zone: Read complete after 2s [id=Z0209050IZW6889EK68H]
```

### Steps to Reproduce

1. `terraform apply`

### Additional notes:
This works with the v0.51.0 version of the aws provider. As a workaround, we fixed the version to this in the provider configuration.
