### ISSUE TITLE
Multiple policy ARNs in aws_iam_group_policy_attachment

### ISSUE THREAD

**Issue by pavlospt** [hashicorp/terraform-provider-aws#20503]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hey! I was migrating our IaC in IAM from Cloudformation to Terraform and I stumbled upon a weird issue! First let me describe how we had our IAM setup in Cloudformation. Cloudformation allows you to reference multiple policies in `ManagedPolicyARN` for an `AWS::IAM::Group`.

So our setup looked something like the following:
```yaml
EnvAppGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "CFNEnvAppSecrets"
      ManagedPolicyArns:
        - !Ref AllParametersManagedPolicy
        - !Ref EnvCommonManagedPolicy
        - !Ref EnvAppManagedPolicy
```

As you can understand from the above example, we have 2 different varying factors which are: `Env` & `App` + some static policies.

In order to re-create the following in Terraform you need to somehow create a matrix between `Env` & `App` and then add the static policies.

I took a quick look at the relevant Go file (`resource_aws_iam_group_policy_attachment.go` IIRC) and was wondering why `policy_arn` cannot be converted to a `schema.TypeList` and be renamed to `policy_arns` or something similar. 

Is there a "background" behind this decision? Could not find something relevant in issues.

If this is also a matter of implementation and you are fine with accepting a PR I think I can open a PR! 

### New or Affected Resource(s)

* aws_iam_group_policy_attachment
