### ISSUE TITLE
Automate removing needs-triage and waiting-response labels from closed issues and PRs

### ISSUE THREAD

**Issue by justinretzolk** [hashicorp/terraform-provider-aws#20948]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In an effort to streamline the triage process, we are considering automating the removal of the `needs-triage` and `waiting-response` labels from closed issues and pull requests via GitHub Actions. While this will largely have no impact on contributors, it should make the triage process a bit less cumbersome, allowing us to focus on the task at hand.

### Proposal

In researching ways to accomplish this, I've found that there are several existing Actions in the GitHub Marketplace focused on automatic label removal. The most active and well maintained of which seems to be [Actions Ecosystem Remove Labels](https://github.com/marketplace/actions/actions-ecosystem-remove-labels). I've tested two main methods for setting up this action, each having its own pros and cons, detailed below.

**Option 1: Single Job**

With this action, if a specified label is not applied to an issue/PR when it is closed, an error will be logged, however, the job will **not** be marked as failed. As such, it's safe to allow the errors to be logged, but may be confusing to anyone reviewing who may be unaware that these errors are expected and benign. The benefit to this is that there is only one job to run in order to remove both labels (and any additional labels, should we choose to expand this effort in the future).

Example:

```yaml
on:
  issues:
    types: [closed]
  pull_request_target:
    types: [closed]
jobs:
  remove-needs-triage-waiting-response:
    runs-on: ubuntu-latest
    steps:
      - name: remove labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            needs-triage
            waiting-response
```

**Option 2: Multiple Jobs Using `strategy.matrix`** Templating

In order to use this action without logging any errors, `strategy.matrix` may be combined with an `if` statement to ensure that the job is only run if the specified label is applied. This has the benefit of not logging any errors at the cost of running a separate job for every label that we'd like to remove. If we were to expand to additional labels in the future, the number of jobs would increase 1:1. 

Example:

```yaml
on:
  issues:
    types: [closed]
  pull_request_target:
    types: [closed]
jobs:
  remove-labels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        labels: ['needs-triage', 'waiting-response']
    steps:
      - name: Remove ${{ matrix.labels }} label
        uses: actions-ecosystem/action-remove-labels@v1
        if: contains(github.event.*.labels.*.name, matrix.labels)
        with:
          labels: ${{ matrix.labels }}
```

### Lingering Questions

The biggest lingering question is which of the above methods would we consider the "best" path forward. **The current thinking is that the `strategy.matrix` method would be better.**

The other question that remains is one of structure/organization; whether these definitions should be added to the existing [issues](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/workflows/issues.yml) and [pull_requests](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/workflows/pull_requests.yml) workflows, or added as a separate workflow. **The current thinking is a separate workflow is probably a better idea.**

If the chosen route is to append to the existing workflows, the `on.pull_request_target` definition in the `pull_request` workflow will need to be adjusted, as `pull_request_target` does not include `closed` by default ([source](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target)). Additionally, the `on.issue.types` definition will need to have `closed` appended.
