### ISSUE TITLE
Migrate github actions workflows to use `actions/setup-go` go-version-file input

### ISSUE THREAD

**Issue by anGie44** [hashicorp/terraform-provider-aws#24937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* Across many of our workflows we setup the go version with following environment variable setup:
```
 # See also: https://github.com/actions/setup-go/pull/62
    - run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    # See also: https://github.com/actions/setup-go/issues/54
```

But as of a recent release in `actions-setup/go` as suggested by @gdavison , this can be accomplished directly as seen in their [github release of v3.1.0](https://github.com/actions/setup-go/releases/tag/v3.1.0) e.g.
```
steps:
 - uses: actions/checkout@v3
 - uses: actions/setup-go@v3
   with:
     go-version-file: 'path/to/go.mod'
 - run: go version
```

### References

* https://github.com/actions/setup-go/pull/62
