### ISSUE TITLE
aws_appflow_flow has too strict validations on task.source_fields

### ISSUE THREAD

**Issue by ulich** [hashicorp/terraform-provider-aws#25095]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.2.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.16.0
```

### Affected Resource(s)

* aws_appflow_flow

### Terraform Configuration Files

```hcl
resource "aws_appflow_flow" "salesforce_to_eventbridge" {
  name = "example"

  source_flow_config {
    connector_type = "Salesforce"
    connector_profile_name = "my-connection"
    source_connector_properties {
      salesforce {
        object = "AccountChangeEvent"
      }
    }
  }

  destination_flow_config {
    connector_type = "EventBridge"
    destination_connector_properties {
      event_bridge {
        object = "aws.partner/appflow/salesforce.com/${data.aws_caller_identity.current.account_id}/example"

        error_handling_config {
          bucket_name = module.large_events_bucket.name
        }
      }
    }
  }

  task {
    task_type         = "Map_all"
    source_fields     = []
    task_properties = {
      EXCLUDE_SOURCE_FIELDS_LIST = "[]"
    }
    connector_operator {
      salesforce = "NO_OP"
    }
  }

  trigger_config {
    trigger_type = "Event"
  }
}

locals {
  large_events_bucket_name = "asdfasdf-appflow-salesforce-large-events"
}

module "large_events_bucket" {
  source  = "terraform-aws-modules/s3-bucket/aws"
  version = "3.2.1"

  bucket = local.large_events_bucket_name
  acl    = "private"

  attach_policy = true
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = {
        Service = "appflow.amazonaws.com"
      }
      Action = [
        "s3:PutObject",
        "s3:GetBucketAcl",
        "s3:PutObjectAcl",
        "s3:AbortMultipartUpload",
        "s3:ListMultipartUploadParts",
        "s3:ListBucketMultipartUploads",
      ]
      Resource = [
        "arn:aws:s3:::${local.large_events_bucket_name}",
        "arn:aws:s3:::${local.large_events_bucket_name}/*",
      ]
    }]
  })
}

```

### Expected Behavior

The flow should be created. The same configuration with CloudFormation works:

```yml
Resources:
  Flow:
    Type: 'AWS::AppFlow::Flow'
    Properties:
      FlowName: example
      SourceFlowConfig:
        ConnectorProfileName: my-connection
        ConnectorType: Salesforce
        SourceConnectorProperties:
          Salesforce:
            Object: AccountChangeEvent
      DestinationFlowConfigList:
        - ConnectorType: EventBridge
          DestinationConnectorProperties:
            EventBridge:
              Object: aws.partner/appflow/salesforce.com/${data.aws_caller_identity.current.account_id}/example
              ErrorHandlingConfig:
                BucketName: module.large_events_bucket.name
      Tasks:
        - TaskType: Map_all
          SourceFields: []
          TaskProperties: 
          - Key: EXCLUDE_SOURCE_FIELDS_LIST
            Value: '[]'
          ConnectorOperator:
            Salesforce: NO_OP
      TriggerConfig:
        TriggerType: Event
```

The goal is to have an appflow that passes each event field 1:1 to event bridge without having to specify each field explicitly.
https://stackoverflow.com/questions/66742683/how-to-map-fields-automatically-in-appflow

### Actual Behavior

The flow is not created with the following validation error:

```
│ Error: creating Appflow Flow (example): InvalidParameter: 1 validation error(s) found.
│ - missing required field, CreateFlowInput.Tasks[0].SourceFields.
│ 
│ 
│   with aws_appflow_flow.salesforce_to_eventbridge,
│   on main.tf line 1, in resource "aws_appflow_flow" "salesforce_to_eventbridge":
│   1: resource "aws_appflow_flow" "salesforce_to_eventbridge" {
```

### Steps to Reproduce

1. `terraform apply`

**Comment by boopathijayagopal** [comment]
I'm also facing the Same issue. is there any values we need to explicitly to Map all the fields from Salesforce to Eventbridge?

**Comment by jrmarquard** [comment]
Also facing the same issue. My work around is to use serverless and define the resource there, does anyone have a terraform workaround?

**Comment by harik8** [comment]
```
  task {
    source_fields   = [""]
    task_type       = "Map_all"
    task_properties = {}
    connector_operator {
      salesforce = "NO_OP"
    }
  }
```
Configuring source_fields as `[""]` works for me. Yet, I get given an error when I run the same terraform code without any changes.
```
invalidParameter: 2 validation error(s) found.
- missing required field, UpdateFlowInput.Tasks[0].SourceFields.
- missing required field, UpdateFlowInput.Tasks[0].TaskType.
```

**Comment by drub4n** [comment]
I'm facing the same issue while trying to update any of my flow, the plan looks correct but apply always end up with the same error. 
Running apply with debug, I found this in the object sent to the appflow API for the flow update :

```
Tasks: [
    {

    },
    {
      ConnectorOperator: { ...}
 ]
```

The first empty object appears everytime I made a change in a flow, even if I don't modify the tasks.

The only way I found to be able to continue working with my flows is to delete the flow and then run `terraform apply` again, this will create a new flow and on On-Demand flow you will loose incremental fetching which is bad with large amounts of data. So it's not a long term solution.

I hope this can help and I can provide more logsif needed .

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 50.0701 USD   attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/29268).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/29268).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,003,876,521.42 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 4 weeks from now.
Please review their action plans below:


**1) [richelleji](https://gitcoin.co/richelleji) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/29268?mutate_worker_action=approve&worker=richelleji) | [reject worker](https://gitcoin.co/issue/29268?mutate_worker_action=reject&worker=richelleji))_.**

Hey I am interested in this task!

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/29268).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 3 weeks, 3 days from now.
Please review their action plans below:


**1) [didiqaz122](https://gitcoin.co/didiqaz122) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/29268?mutate_worker_action=approve&worker=didiqaz122) | [reject worker](https://gitcoin.co/issue/29268?mutate_worker_action=reject&worker=didiqaz122))_.**

goodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgoodgood

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/29268).

**Comment by pitt-william-t** [comment]
I am also facing this problem. This should be straightforward!

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 2 days, 10 hours from now.
Please review their action plans below:


**1) [fredydev](https://gitcoin.co/fredydev) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/29268?mutate_worker_action=approve&worker=fredydev) | [reject worker](https://gitcoin.co/issue/29268?mutate_worker_action=reject&worker=fredydev))_.**

please let me know if you already find someone for this task

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/29268).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 50.07 USD (50.00 USD @ $1.0/USD) has been submitted by__:

 1. [@fredydev](https://gitcoin.co/fredydev)



@camro please take a look at the submitted work:
* [PR](https://github.com/fredydev/appflow_aws) by @fredydev

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/29268)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/29268).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://discord.gg/gitcoin/'>Gitcoin's Discord</a>
* $1,003,375,911.64 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by camro** [comment]
@freddygv can you point to the PR?

**Comment by n11c** [comment]
Any progress with this?  
@camro's [PR](https://github.com/hashicorp/terraform-provider-aws/pull/26614/files) seems to solve the issue.  
Any chance to see it merged and released soon?

**Comment by camro** [comment]
@n11c can you put a thumbs up on the PR comment?

**Comment by kk-nutmeg** [comment]
facing a similar issue, Any plans to release this fix soon? until then any workaround to create an appflow task using `Map_all`

**Comment by JasonSqz** [comment]
Facing the same issue, found a workaround by deleting the specific appflow each time I reran terraform apply

**Comment by boyardean** [comment]
Same issue, offering up this workaround in case it helps anyone: make use of the [lifecycle meta argument](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle). Specifically, the `ignore_changes` arg

```
lifecycle {
  ignore_changes = [
    task
  ]
}
```

**Comment by Rhexis** [comment]
I've also encountered the same issue. Workaround was to create an `aws_cloudformation_stack` resource which created the Appflow Flow instead of using the `aws_appflow_flow` resource. Not a fan of this at all, having to come up with workarounds is pretty unacceptable. When can we see the PR by @camro merged?

**Comment by walloul-ipsen** [comment]
Facing the same issue on my side, can't deploy Appflow task with Map_all twice without changes. This is really annoying and should not be such a pain to make this work.

**Comment by togakangaroo** [comment]
The above-mentioned PR is merged (at least according to tags). Unfortunately, upgrading to aws provider 5.12 doesn't solve the issue. When I ignore tasks that gets me past the initial required field error at `tasks[0]`, but gives me *another* one at a further down index for some reason. I suspect that was  yet another bug.

However, due to [this issue](https://github.com/hashicorp/terraform-provider-aws/issues/25085) it seems like I wouldn't be able to actually activate the appflow anyways. 

The workaround of dropping down to cloudformation seems to work on limited testing
```
resource "aws_cloudformation_stack" "gim_test_appflow" {
  name = "gim-test-stack-appflow"

  parameters = {
    FlowName =  "gim-test-applflow"
  }

  template_body = <<-EOT
  Parameters:
    FlowName:
      Type: String
  Resources:
    AppFlow:
      Type: 'AWS::AppFlow::Flow'
      Properties:
        FlowName:
          Ref: FlowName
        TriggerConfig:
          TriggerType: OnDemand
        SourceFlowConfig:
          ConnectorType: Salesforce
          ConnectorProfileName: SFDC-${local.tenant_name}
          SourceConnectorProperties:
            Salesforce:
              Object: LeadChangeEvent
              EnableDynamicFieldUpdate: false
              IncludeDeletedRecords: false
        DestinationFlowConfigList:
          - ConnectorType: EventBridge
            ConnectorProfileName: ${var.partner_event_source[local.tenant_name]}
            DestinationConnectorProperties:
              EventBridge:
                Object: ${var.partner_event_source[local.tenant_name]}
        Tasks:
          - TaskType: Map_all
            SourceFields: []
            TaskProperties:
              - Key: EXCLUDE_SOURCE_FIELDS_LIST
                Value: '[]'
            ConnectorOperator:
              Salesforce: NO_OP
  EOT
}
```
