### ISSUE TITLE
Error: error configuring Terraform AWS Provider: failed to get shared config profile (only happens on version 4 and above)

### ISSUE THREAD

**Issue by jonathanprior** [hashicorp/terraform-provider-aws#25905]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

The provider

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.22"
    }
  }
  required_version = ">= 1.1.7"
}

```

### Expected Behavior

`terraform plan` should run

### Actual Behavior

```
Error: error configuring Terraform AWS Provider: failed to get shared config profile, test-1  with provider["registry.terraform.io/hashicorp/aws"],
  on provider.tf line 1, in provider "aws":
   1: provider "aws" {
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Rolling back to `version = "~> 3.0"` fixes the issue. This [post was created](https://github.com/hashicorp/terraform-provider-aws/issues/23110), but no clear resolution was made.

**Comment by jonathanprior** [comment]
Figured out the solution

In the GitHub Actions file, we had something like:

```
- name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v1
  with:
    aws-region: us-east-1
    aws-access-key-id: ${{ secrets.YOUR_ACCESS_KEY }}
    aws-secret-access-key: ${{ secrets.YOUR_SECRET_ACCESS_KEY }}
```

I had to remove this and change it to authenticate through aws configure as seen below:
```
- name: Add profile credentials to ~/.aws/credentials
  run: |
    aws configure set aws_access_key_id ${{ secrets.YOUR_ACCESS_KEY }} --profile test-1
    aws configure set aws_secret_access_key ${{ secrets.YOUR_SECRET_ACCESS_KEY }} --profile test-1
```
