### ISSUE TITLE
Terraform init on CodeBuild "no valid credential sources for S3 Backend found."

### ISSUE THREAD

**Issue by marian-gheorghe** [hashicorp/terraform-provider-aws#26455]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform 1.2.7
AWS Provider 3.75.2

### Affected Resource(s)

S3 Backend Config

### Terraform Configuration Files
I have AWS CodeBuild which is assuming role devops

**codebuild.tf**
```hcl
resource "aws_codebuild_project" "code_build" {
  name          = "${var.app_name}-${var.target_env}-${var.build_project}"
  description   = "${var.app_name} ${var.build_project} pipeline on ${var.target_env}"
  service_role  = arn:aws:iam::xxxxx:role/devops
....
```

`devops` role has a policy that allows to be assumed by codebuild service and comes with admin privileges

```hcl
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "",
                "Effect": "Allow",
                "Principal": {
                    "Service": "codebuild.amazonaws.com"
                },
                "Action": "sts:AssumeRole"
            }
        ]
    }
```

**Admin privileges**

```hcl
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": "*",
                "Resource": "*"
            }
        ]
    }
```

**Terraform backend config**

```hcl
    terraform {
      required_providers {
        aws = {
          source  = "hashicorp/aws"
          version = "~>3.0"
        }
      }
      
      backend "s3" {
        bucket         = "tfstatebucket"
        key            = "infrastructure/terraform.tfstate"
        region         = "eu-central-1"
        dynamodb_table = "cdc-terraform-up-and-running-lock"
        encrypt        = true
      }
    }
    
    provider "aws" {
      region = lookup(var.aws_region, var.env)
    
      allowed_account_ids = [
        lookup(var.account_id, var.env),
      ]
    }
 ```
 
 **Ohter configs**
 
 `Buildspec.yaml`

```yaml
    version: 0.2
    
    phases:
      install:
        commands:
          - |
            if [ -n "$INSTALL_TOOLS_SCRIPT" ]; then
              ./$INSTALL_TOOLS_SCRIPT
            fi
      pre_build:
        commands:
          - |
            if [ -n "$PREBUILD_SCRIPT" ]; then
              ./$PREBUILD_SCRIPT
            fi
      build:
        commands:
          - |
            if [ -n "$BUILD_SCRIPT" ]; then
              ./$BUILD_SCRIPT
            fi
      post_build:
        commands:
          - |
            if [ -n "$POSTBUILD_SCRIPT" ]; then
              ./$POSTBUILD_SCRIPT
            fi
```

`install_tools.sh`

```bash
    #!/bin/bash
    set -euxo pipefail
    
    function install_terraform() {
        echo Installing Terraform...
        
        curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.2.7/terraform_1.2.7_linux_amd64.zip
        unzip terraform_install.zip -d /usr/bin/
        chmod +x /usr/bin/terraform
    
        terraform --version 
    }
    
    install_terraform
```

`prebuild.sh`

```bash
    set -euxo pipefail
    
    echo Terraform init...
    terraform init
```

### Expected Behavior

`terraform init` should succeed

### Actual Behavior

```
Terraform init...
+ terraform init
Initializing modules...
- aws_appautoscaling_ecs_consumer_target in tfmodules/autoscaling
- aws_appautoscaling_ecs_server_target in tfmodules/autoscaling
- aws_appautoscaling_ecs_websocket_server_target in tfmodules/autoscaling
 
Initializing the backend...

 Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.

 Please see https://www.terraform.io/docs/language/settings/backends/s3.html
 for more information about providing credentials.

 Error: NoCredentialProviders: no valid providers in chain. Deprecated.
   For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
### DEBUG LOG
[
Debug Log Gist
](https://gist.github.com/marian-gheorghe/e45e460435d2481ded8c7b217b2f9c5b)

### Steps to Reproduce

1. `terraform init`

### Important Factoids

It works fine on local machine after successfully assuming the `devops` role. It doesn't work on CodeBuild 
CodeBuild is configured in a private VPC (VPC with only private subnets)

### References

* #0000
