### ISSUE TITLE
TF Output is not updated, when aws_servicecatalog_provisioned_product replaces a resource

### ISSUE THREAD

**Issue by micweg1** [hashicorp/terraform-provider-aws#26549]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.9
registry.terraform.io/hashicorp/aws: 4.28.0 (latest)

### Terraform Configuration Files

**Service Catalog Product Yaml File**
```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Sumit Initial CloudFormation script

Parameters:
  AwsLogicalAccountNameLowerCase:
    Description: Logical AWS account name e.g. kush
    Type: String

Resources:
################S3 Buckets################
  KushResourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['', [!Ref AwsLogicalAccountNameLowerCase, '-learning-1000-resouces']]
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
          BlockPublicAcls: True
          BlockPublicPolicy: True
          IgnorePublicAcls: True
          RestrictPublicBuckets: True

################S3 Bucket Policies################
  KushResourceBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KushResourceBucket
      PolicyDocument:
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: '*'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref AwsLogicalAccountNameLowerCase, '-learning-1000-resouces/*']]
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal: '*'
            Action:
              - s3:PutObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref AwsLogicalAccountNameLowerCase, '-learning-1000-resouces/*']]
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: AES256
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action:
              - s3:PutObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref AwsLogicalAccountNameLowerCase, '-learning-1000-resouces/*']]
            Condition:
              'Null':
                s3:x-amz-server-side-encryption: true
          - Sid: DenyUnwantedCannedACLs
            Effect: Deny
            Principal: '*'
            Action:
              - s3:PutObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref AwsLogicalAccountNameLowerCase, '-learning-1000-resouces/*']]
            Condition:
              StringEquals:
                s3:x-amz-acl:
                  - public-read
                  - public-read-write
                  - aws-exec-read
                  - authenticated-read
                  - bucket-owner-read
                  - log-delivery-write

Outputs:
  BucketName:
    Description: Ref to the Bucket Name
    Value: !Ref KushResourceBucket

  BucketArn:
    Description: Bucket Arn
    Value: !GetAtt KushResourceBucket.Arn`
```

### Terraform Configuration Files

```hcl
#provider.tf

provider "aws" {
  region = "eu-central-1"
}
```

```hcl
#variables.tf

variable "product_id" {
  description = "Enter Product_Id"
  type        = string
  default     = "prod-yyvg6iyzlz6de"
}

variable "provisioning_artifact_id" {
  description = "Enter provisioning_artifact_id"
  type        = string
  default     = "pa-atcnxryqztky6"
}

variable "aws_logical_account_name_lower_case" {
  description = "Enter aws_logical_account_name_lower_case"
  type        = string
  default     = "michael-v2"
}

variable "provisioned_product_name" {
  description = "Enter provisioned_product_name"
  type        = string
  default     = "Bucket_Creation_michael"
}
```

```hcl
#main.tf

# Provisioning Service Catalog Product
resource "aws_servicecatalog_provisioned_product" "s3_bucket" {
  // Product Name
  name         = var.provisioned_product_name

  # Service catalog parameters
  product_id                = var.product_id
  provisioning_artifact_id  = var.provisioning_artifact_id
  // Service catalog provisioning parameters

  provisioning_parameters {
    key   = "AwsLogicalAccountNameLowerCase"
    value = var.aws_logical_account_name_lower_case
  }

}

locals {
  depends_on = [
    aws_servicecatalog_provisioned_product.s3_bucket
  ]
  pp_obtained_outputs = {
    for output in aws_servicecatalog_provisioned_product.s3_bucket.outputs : output.key =>
    output.value if contains(
      [ "BucketName",
        "BucketArn"],
    output.key)
  }
}

output "BucketName" {
  value       = local.pp_obtained_outputs["BucketName"]
  description = "Outputs the Bucket Name"
}

output "BucketArn" {
  value       = local.pp_obtained_outputs["BucketArn"]
  description = "Outputs the Bucket BucketArn"
}

```

### Expected Behavior

The module creates a Service Catalog provisioned product, which creates an S3 Bucket. The Bucket name is taken from the variable "aws_logical_account_name_lower_case". The Provisioned Product then outputs the ARN and the Bucket Name. The outputs of the Service Catalog Provisioned Product are then fetched and outputted by the Terraform module (in main.tf).

If we change the desired Bucket name from the variable, the Provisioned Product should be updated, destroying the old bucket, creating a new one, updating the output and Terraform should fetch the new ARN and Bucket Name that are outputted by the Service Catalog Provisioned Product..

### Actual Behavior

On the first apply, the Bucket is created and the output is correct.
When the Bucket Name is changed by the variable in Terraform, the Provisoned Product is correctly updated: The Bucket is replaced and the Service Catalog Output is also updated. But the Terraform Output is not updated. It still reflects the old status (old Bucket Name and ARN).

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

The Provisioned Product including the Bucket is created correctly. Terraform gives the right output.

5. `Change Bucket name in the variables.tf`

Now, we change the Bucket name by modifying the variable "aws_logical_account_name_lower_case" (e.g. from my-bucket-1 to my-bucket-2)

6. `terraform plan`

Terraform will show that it wants to update the Service Catalog Provisioned Product. It does not display that there might be possible changes on the output.

7. `terraform apply`

The Provisioned Product is updated correctly. The Bucket is replaced and the Output of the Service Catalog Provisioned Product is updated. Nevertheless, Terraform does not fetch the updated output and still keeps the old one (e.g. in case of the Bucket Name output, it would keep "my-bucket-1" and would not update to "my-bucket-2)
