### ISSUE TITLE
[Bug]: aws_inspector2_enabler uses wrong status api

### ISSUE THREAD

**Issue by aa-ron-arnott** [hashicorp/terraform-provider-aws#27644]
### Terraform Core Version

1.1.9

### AWS Provider Version

4.37.0

### Affected Resource(s)

aws_inspector2_enabler

### Expected Behavior

The resource should enable, the specified resource scanning, **AND inspector2** in the designated accounts. The resource should be using the [BatchGetAccountStatus](https://docs.aws.amazon.com/inspector/v2/APIReference/API_BatchGetAccountStatus.html) api instead of the Disable api.

### Actual Behavior

The status checks using the `Disable` api make it so that the resource scanning ends up enabled, but the inspector2 status is **disabled** in the target account.

We see the response from this part of the get status code. https://github.com/hashicorp/terraform-provider-aws/blob/3cf15a22d8e393d5e7439c2f4d2cb75ed92d6ceb/internal/service/inspector2/enabler.go#L260-L266

It starts as this
```yaml
    "responseElements": {
        "failedAccounts": [],
        "accounts": [
            {
                "accountId": "--REDACTED--",
                "resourceStatus": {
                    "ec2": "ENABLING",
                    "ecr": "ENABLING"
                },
                "status": "ENABLING"
            }
        ]
    },
```

And the response to the final `Disable` request shows like this
```yaml
        "failedAccounts": [
            {
                "accountId": "--REDACTED--",
                "errorCode": "RESOURCE_SCAN_NOT_DISABLED",
                "errorMessage": "Resource level scanning must be disabled before Inspector can be disabled.",
                "resourceStatus": {
                    "ec2": "ENABLED",
                    "ecr": "ENABLED"
                },
                "status": "DISABLED"
            }
        ],
```

Note that `status` has gone from `ENABLING` to `DISABLED`.

### Terraform Configuration Files

```terraform
data "aws_caller_identity" "current" {}

resource "aws_inspector2_enabler" "this" {
  account_ids    = [data.aws_caller_identity.current.account_id]
  resource_types = ["ECR", "EC2"]
}
```

### Steps to Reproduce

1. Have an account where Inspector V2 is disabled
2. Run the terraform config against it.
3. Inspect the CloudTrail events for the `Disable` event, they should show the resource progressing from `ENABLING` to `ENABLED` to `DISABLING` and `DISABLED` though the `ec2` and `ecr` resource status will finalize on `ENABLED`

### References

The resource status checks in question: https://github.com/hashicorp/terraform-provider-aws/blob/3cf15a22d8e393d5e7439c2f4d2cb75ed92d6ceb/internal/service/inspector2/enabler.go#L260-L266

The recommended AWS API: https://docs.aws.amazon.com/inspector/v2/APIReference/API_BatchGetAccountStatus.html

### Would you like to implement a fix?

No
