### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ashish-mokashe** [hashicorp/terraform-provider-aws#31977]
### Terraform Core Version

1.3.7

### AWS Provider Version

v4.64.0

### Affected Resource(s)

aws_glue_trigger

```terraform
resource "aws_glue_trigger" "schedule_crawler" {
  for_each = local.workflows
  name = "${local.resource_prefix_hyphen}-${each.key}-schedule-crawler"
  type = "SCHEDULED"
  schedule = each.value.schedule_trigger.schedule


  dynamic "actions" {
    for_each = each.value.schedule_trigger.crawler_actions
    content {
      crawler_name= actions.value.crawler_name
    }
  }
}
```

Config:
```
global-partner:
  description: Ingest partner data from all businesses and runs matching process to generate Global Partner ID
  schedule: cron(15 6 * * ? *)

  schedule_trigger:
      schedule: cron(15 6 * * ? *)
      crawler_actions:
        - crawler_name: ${crawler_sugarcrm_accounts}
        - crawler_name: ${crawler_sugarcrm_account_types}
        - crawler_name: ${crawler_reference_data}
        - crawler_name: ${crawler_ust_partner}
        - crawler_name: ${crawler_giacom_users_business}
        - crawler_name: ${crawler_giacom_users_contact}

```

### Expected Behavior

A trigger is created with multiple crawler as actions

Plan output is:

```shell
  # aws_glue_trigger.schedule_crawler["global-partner"] will be created
  + resource "aws_glue_trigger" "schedule_crawler" {
      + arn      = (known after apply)
      + enabled  = true
      + id       = (known after apply)
      + name     = "dev-cdp-global-partner-schedule-crawler"
      + schedule = "cron(15 6 * * ? *)"
      + state    = (known after apply)
      + tags_all = (known after apply)
      + type     = "SCHEDULED"

      + actions {
          + crawler_name = "dev-cdp-dc-sugarcrm-accounts"
        }
      + actions {
          + crawler_name = "dev-cdp-dc-sugarcrm-account-types"
        }
      + actions {
          + crawler_name = "dev-cdp-s3-referencedata"
        }
      + actions {
          + crawler_name = "dev-cdp-s3-ust_partner"
        }
      + actions {
          + crawler_name = "dev-cdp-giacom-messageexchange-users-business"
        }
      + actions {
          + crawler_name = "dev-cdp-giacom-messageexchange-users-contact"
        }
    }

```

### Actual Behavior

Terraform apply fails with below error. I can created trigger with multiple crawler action straight on AWS Console.

```shell
╷
│ Error: creating Glue Trigger (dev-cdp-global-partner-schedule-crawler): InvalidInputException: Actions cannot contain more than 2 crawlers
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "6dc37529-44fd-4945-9ef5-5718c997162f"
│   },
│   Message_: "Actions cannot contain more than 2 crawlers"
│ }
│
│   with aws_glue_trigger.schedule_crawler["global-partner"],
│   on partner_matching.tf line 106, in resource "aws_glue_trigger" "schedule_crawler":
│  106: resource "aws_glue_trigger" "schedule_crawler" {
│

```

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: creating Glue Trigger (dev-cdp-global-partner-schedule-crawler): InvalidInputException: Actions cannot contain more than 2 crawlers
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "6dc37529-44fd-4945-9ef5-5718c997162f"
│   },
│   Message_: "Actions cannot contain more than 2 crawlers"
│ }
│
│   with aws_glue_trigger.schedule_crawler["global-partner"],
│   on partner_matching.tf line 106, in resource "aws_glue_trigger" "schedule_crawler":
│  106: resource "aws_glue_trigger" "schedule_crawler" {
│
```

### Terraform Configuration Files

```terraform
resource "aws_glue_trigger" "schedule_crawler" {
  for_each = local.workflows
  name = "${local.resource_prefix_hyphen}-${each.key}-schedule-crawler"
  type = "SCHEDULED"
  schedule = each.value.schedule_trigger.schedule


  dynamic "actions" {
    for_each = each.value.schedule_trigger.crawler_actions
    content {
      crawler_name= actions.value.crawler_name
    }
  }
}
```

Config:

```
global-partner:
  description: Ingest partner data from all businesses and runs matching process to generate Global Partner ID
  schedule: cron(15 6 * * ? *)

  schedule_trigger:
      schedule: cron(15 6 * * ? *)
      crawler_actions:
        - crawler_name: ${crawler_sugarcrm_accounts}
        - crawler_name: ${crawler_sugarcrm_account_types}
        - crawler_name: ${crawler_reference_data}
        - crawler_name: ${crawler_ust_partner}
        - crawler_name: ${crawler_giacom_users_business}
        - crawler_name: ${crawler_giacom_users_contact}
```

### Steps to Reproduce

1. Create a config
2. create aws_glue_trigger resource with dynamic `actions` block

### Would you like to implement a fix?

None
