### ISSUE TITLE
[Enhancement]: Glue Connections ought to support third-party kafka authentication methods

### ISSUE THREAD

**Issue by mforeman19** [hashicorp/terraform-provider-aws#32459]
### Description

Glue Connections via Terraform do not support all authentications types to third-party kafka clusters. Via the console, it looks like this:

![image](https://github.com/hashicorp/terraform-provider-aws/assets/48162520/b2fd44a1-019e-4374-8a7a-75771e79fc0c)

Where SASL does not appear to be supported. I would expect that you could do it like the following:

```
resource "aws_glue_connection" "test" {
  name = "test"

  connection_type = "KAFKA"
  connection_properties = {
    KAFKA_BOOTSTRAP_SERVERS = "bootstrap_servers"
    KAFKA_SASL_MECHANISM    = "SCRAM-SHA-512"
    SECRET_ID               = "secret_id"
    KAFKA_SSL_ENABLED       = false
  }

  physical_connection_requirements {
    availability_zone      = "zone_a"
    security_group_id_list = ["sg"]
    subnet_id              = "subnet_a"
  }
}
```

But it results in this error:

```
Error: expected connection_properties to be one of [HOST PORT USERNAME PASSWORD ENCRYPTED_PASSWORD JDBC_DRIVER_JAR_URI JDBC_DRIVER_CLASS_NAME JDBC_ENGINE JDBC_ENGINE_VERSION CONFIG_FILES INSTANCE_ID JDBC_CONNECTION_URL JDBC_ENFORCE_SSL CUSTOM_JDBC_CERT SKIP_CUSTOM_JDBC_CERT_VALIDATION CUSTOM_JDBC_CERT_STRING CONNECTION_URL KAFKA_BOOTSTRAP_SERVERS KAFKA_SSL_ENABLED KAFKA_CUSTOM_CERT KAFKA_SKIP_CUSTOM_CERT_VALIDATION KAFKA_CLIENT_KEYSTORE KAFKA_CLIENT_KEYSTORE_PASSWORD KAFKA_CLIENT_KEY_PASSWORD ENCRYPTED_KAFKA_CLIENT_KEYSTORE_PASSWORD ENCRYPTED_KAFKA_CLIENT_KEY_PASSWORD SECRET_ID CONNECTOR_URL CONNECTOR_TYPE CONNECTOR_CLASS_NAME], got KAFKA_SASL_MECHANISM
```

### Affected Resource(s) and/or Data Source(s)

aws_glue_connection

### Potential Terraform Configuration

```terraform
resource "aws_glue_connection" "test" {
  name = "test"

  connection_type = "KAFKA"
  connection_properties = {
    KAFKA_BOOTSTRAP_SERVERS = "bootstrap_servers"
    KAFKA_SASL_MECHANISM    = "SCRAM-SHA-512"
    SECRET_ID               = "secret_id"
    KAFKA_SSL_ENABLED       = false
  }

  physical_connection_requirements {
    availability_zone      = "zone_a"
    security_group_id_list = ["sg"]
    subnet_id              = "subnet_a"
  }
}
```

### References

If you were to use Cloudformation, you could input these like so:

```
Resources:
  myGlueConnection:
    Type: 'AWS::Glue::Connection'
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      ConnectionInput:
        ConnectionProperties:
          KAFKA_BOOTSTRAP_SERVERS: 'boot.us-east-1.amazonaws.com:9098'
          KAFKA_SASL_MECHANISM: SCRAM-SHA-512
          SECRET_ID: test
          KAFKA_SSL_ENABLED: 'false'
        ConnectionType: KAFKA
```

And I can successfully make a glue connection using SASL/SCRAM-SHA-512

### Would you like to implement a fix?

None
