### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by craymont94** [hashicorp/terraform-provider-aws#34372]
### Terraform Core Version

1.6.3

### AWS Provider Version

4.67.0

### Affected Resource(s)

* aws_cloudformation_stack

### Expected Behavior

When creating change set for CloudFormation stack with an updated version of the template which includes a new condition that doesn't change the current configuration of the stack you get an AWS error (when creating change sset in the console):

```
The submitted information didn't contain changes. Submit different information to create a change set.
```

This prevents you creating the change set in the console. Expected behaviour is that when applying such changes with terraform the apply fails with a similar error.

### Actual Behavior

When performing the same change using terraform the changes in the cloudformation template show in the plan and are applied successfully to the account. However, when checking in the console no change set has been created and the template is not updated.

### Terraform Configuration Files

**Original confiuration:**

```
resource "aws_cloudformation_stack" "codeguru_profiler" {
  name          = "codeguruProfilerStack"
  count         = var.codeguru_profiler ? 1 : 0
  template_body = file("${path.module}/profiler_cloudformation.yml")
  parameters = {
    ServiceOneAgentRole = aws_iam_role.service_one.arn,
    ServiceTwoAgentRole = aws_iam_role.service_two.arn
  }
}
```

Original template

```
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates two Cloudguru profiling groups,
  one each for the ServiceOne and ServiceTwo APIs

Parameters:
  ServiceOneAgentRole:
    Type: String
  ServiceTwoAgentRole:
    Type: String

Resources:
  ServiceOneProfilingGroup:
    Type: AWS::CodeGuruProfiler::ProfilingGroup
    Properties:
      ComputePlatform: "Default"
      ProfilingGroupName: "ServiceOneProfilingGroup"
      AgentPermissions:
        Principals:
          - Ref: ServiceOneAgentRole


  ServiceTwoProfilingGroup:
    Type: AWS::CodeGuruProfiler::ProfilingGroup
    Properties: 
      ComputePlatform: "Default"
      ProfilingGroupName: "ServiceTwoProfilingGroup"
      AgentPermissions:
        Principals:
          - Ref: ServiceTwoAgentRole
```

**Updated Terraform (a new toggle is introduced for resources relating to Service Two)**

CloudFormation Stack resource definition

```
resource "aws_cloudformation_stack" "codeguru_profiler" {
  name          = "codeguruProfilerStack"
  count         = var.codeguru_profiler ? 1 : 0
  template_body = file("${path.module}/profiler_cloudformation.yml")
  parameters = {
    ServiceOneAgentRole = aws_iam_role.service_one.arn,
    // "N/A" is passed to the template to indicate we don't want to create Service Two profiling group
    ServiceTwoAgentRole = var.service_two_resources ? "N/A" : aws_iam_role.service_two[count.index].arn
  }
}
```

Updated template:

```
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates two Cloudguru profiling groups,
  one each for the ServiceOne and ServiceTwo APIs

Parameters:
  ServiceOneAgentRole:
    Type: String
  ServiceTwoAgentRole:
    Type: String

Conditions:
  CreateServiceTwoResources: !Not
    - !Equals
      - !Ref ServiceTwoAgentRole
      - 'N/A'

Resources:
  ServiceOneProfilingGroup:
    Type: AWS::CodeGuruProfiler::ProfilingGroup
    Properties:
      ComputePlatform: "Default"
      ProfilingGroupName: "ServiceOneProfilingGroup"
      AgentPermissions:
        Principals:
          - Ref: ServiceOneAgentRole


  ServiceTwoProfilingGroup:
    Type: AWS::CodeGuruProfiler::ProfilingGroup
    Condition: CreateServiceTwoResources
    Properties: 
      ComputePlatform: "Default"
      ProfilingGroupName: "ServiceTwoProfilingGroup"
      AgentPermissions:
        Principals:
          - Ref: ServiceTwoAgentRole
```

### Steps to Reproduce

1. Plan and apply terraform with original terraform (stack creates)
2. Plan and apply terraform with updated terraform with variable `service_two_resources` set to true
3. Apply completes but observe no change set created in the console at the time of apply
4. Attempt the change to the template in the console with same environment variables in cloudformation stack observe AWS error

### Would you like to implement a fix?

None
