### ISSUE TITLE
[Enhancement]: Appsync targets for aws_cloudwatch_event_target

### ISSUE THREAD

**Issue by jarrod-mg** [hashicorp/terraform-provider-aws#36369]
### Description

AWS Cloudwatch Event Targets can use AWS AppSync GraphQL APIs as a target. To do so, you need to set the ARN to, for example, "arn:aws:appsync:ap-southeast-2:0123456789012:endpoints/graphql-api/GRAPHQLENDPOINTIDSTRING", and also set a block "AppSyncParameters". The cloudformation inside a cloudwatch event rule looks like:

```yaml
  Targets:
        - Id: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
          Arn: >-
            arn:aws:appsync:ap-southeast-2:xxxxxxxxxxx:endpoints/graphql-api/xxxxxxxxxxxxxxxxxxxxxx
          RoleArn: >-
            arn:aws:iam::xxxxxxxxxxx:role/service-role/Amazon_EventBridge_Invoke_AppSync_xxxxxxxxxxx
          InputTransformer:
            InputPathsMap:
              field: $.detail.field
            InputTemplate: |-
              {
                "input": {"hash": "<field>"}
              }
          AppSyncParameters:
            GraphQLOperation: >-
              mutation
              myMutation($input:MyInput!){theMutation(input:$input){
                hash
              }}
```      

### Affected Resource(s) and/or Data Source(s)

* aws_cloudwatch_event_target

### Potential Terraform Configuration

```terraform
resource "aws_cloudwatch_event_target" "target" {
  rule = "MyRuleName"
  arn  = "arn:aws:appsync:ap-southeast-2:0123456789012:endpoints/graphql-api/GRAPHQLENDPOINTIDSTRING"
  event_bus_name = "MyEventBus"
  role_arn = aws_iam_role.MyRole.arn

  input_transformer {
    input_paths = {
      "thing": "$.detail.thing"
    }
    input_template = jsonencode({
      input: {
        thing: "<thing>"
      }
    }
  }

  app_sync_parameters {
    graphql_operation = "mutation myMutation($input: Input!){theMutation(input: $input){ output }}"
}
```

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-appsyncparameters.html

### Would you like to implement a fix?

No
