### ISSUE TITLE
[Enhancement]: Output from ServiceCatalog execution should change after ServiceCatalog update ?

### ISSUE THREAD

**Issue by florian0410** [hashicorp/terraform-provider-aws#37219]
### Description

When I'm updating a provisioned product using a new artifact id or product version, even when the outputs are not supposed to change terraform will return changes **Known after apply only**.

For ex, when using a new version of a product in a provisioned product, and the outputs is not expected to change, we see the following. 

```
Changes to Outputs:
  ~ InstanceID = "i-0041411f2e212969e" -> (known after apply)
...
...
...
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

InstanceID = "i-0041411f2e212969e"
```

Problem is that if you rely on these outputs in another resource ,a load balancer as an example, terraform will detach the instance from the load balancer before reattaching it leading to a service interruption when it should not have been.

**Our main need here is to ensure the load balancer is not removing the entry until it's sure it needs it.** Known after apply should not remove then re-add the ressource

How could we enhance or evolve terraform behavior to resolve such issue ?

**Reproduction**
- Create a product using the following Cloudformation template
```
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create an EC2 instance

Parameters:
  InstanceAMIId:
    Type: String
    Description: Enter the AMI ID for the EC2 instance

  SubnetId:
    Type: String
    Description: Enter the Subnet ID for the EC2 instance

  VpcId:
    Type: String
    Description: Enter the VPC ID for the EC2 instance

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref InstanceAMIId
      SubnetId: !Ref SubnetId
      InstanceType: t2.micro # Replace with your desired instance type
      SecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId

  # Add a security group resource using the provided VPC ID in parameters
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceID:
    Value: !Ref MyEC2Instance
  PrivateIP:
    Value: !GetAtt MyEC2Instance.PrivateIp

```

- Instantiate a provisioned product using the created product
- Check outputs
- Upload manually the same Cloudformation template in the product as a new version
- Update terraform code by changing artifact id accordingly
- Observe the Output being "Known after apply" but not changed as a result, since the template remain the same the output should not change and impact any linked resources

### Affected Resource(s) and/or Data Source(s)

aws_servicecatalog_provisioned_product
aws_lb
aws_lb_target_group
aws_lb_target_group_attachment

### Potential Terraform Configuration

```terraform
# Module for creating the EC2 from ServiceCatalog
# module MyEC2

resource "aws_servicecatalog_product" "example" {
  name        = "example-product"
  owner       = "example-owner"
  description = "example-description"
  distributor = "example-distributor"
  support_description = "example-support-description"
  support_email       = "example-support-email@test.com"
  support_url         = "http://example-support-url.com"
  tags = {
    "example-key" = "example-value"
  }
  type = "CLOUD_FORMATION_TEMPLATE"
  provisioning_artifact_parameters {
    template_url = "PROVIDE_YOUR_TEMPLATE_S3_URL"
    type = "CLOUD_FORMATION_TEMPLATE"
  }  
}


resource "aws_servicecatalog_product_portfolio_association" "example" {
  portfolio_id = "port-xxxxxxx" # Provide your portfolio created
  product_id   = aws_servicecatalog_product.example.id
}

resource "aws_servicecatalog_provisioned_product" "example" {
  name                       = aws_servicecatalog_product.example.name
  product_name               = "example-product"
  provisioning_artifact_id = "pa-xxxxxxxx" # Manual entry after product creation only (second apply required

  provisioning_parameters {
    key   = "InstanceAMIId"
    value = "ami-xxxxxxxxxxxxx"
  }

  provisioning_parameters {
    key   = "SubnetId"
    value = "subnet-xxxxxxxxxxxx"
  }

  provisioning_parameters {
    key   = "VpcId"
    value = "vpc-xxxxxxxxx"
  }  

}


resource "aws_servicecatalog_provisioned_product" "example2" {
  name                       = "example2"
  product_name               = "example-product"
  provisioning_artifact_id = "pa-xxxxxxxxx" # Manual entry after product creation only (second apply required

  provisioning_parameters {
    key   = "InstanceAMIId"
    value = "ami-xxxxxxxxxxx"
  }

  provisioning_parameters {
    key   = "SubnetId"
    value = "subnet-xxxxxxxxxx"
  }

  provisioning_parameters {
    key   = "VpcId"
    value = "vpc-xxxxxxxx"
  }  

}

output "InstanceID" {
  value       = [for output in aws_servicecatalog_provisioned_product.example.outputs : output.value if output.key == "InstanceID"][0]
  description = "Outputs the EC2 Instance ID of Created Instance"
}
output "InstanceID2" {
  value       = [for output in aws_servicecatalog_provisioned_product.example2.outputs : output.value if output.key == "InstanceID"][0]
  description = "Outputs the EC2 Instance ID of Created Instance"
}

# Another module which manage the load balancer side relying on the previous module

### Theory, not working probably

resource "aws_lb_target_group" "test" {
  name     = "tf-example-lb-tg"
  port     = 80
  protocol = "HTTP"
  vpc_id   = vpc-xxxxxxxxx
  target_type = "instance"
}

resource "aws_lb_target_group_attachment"
"tg_attachment_test" {
    target_group_arn = aws_lb_target_group.test.arn
    target_id        = module.myEC2.instanceID # this is causing the problematic behavior Know after change
    port             = 80
}
```

### Would you like to implement a fix?

None
