### ISSUE TITLE
[Bug]: `aws_security_group` resource is created with an invalid egress rule

### ISSUE THREAD

**Issue by nikpivkin** [hashicorp/terraform-provider-aws#38316]
### Terraform Core Version

1.8.5

### AWS Provider Version

5.57.0

### Affected Resource(s)

aws_security_group

### Expected Behavior

The resource is successfully created if one of the following arguments is not specified for the rule egress: cidr_blocks, ipv6_cidr_blocks, prefix_list_ids, or security_groups.

### Actual Behavior

A resource should not be created.

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
    }
  }

  required_version = ">= 1.2.0"
}

provider "aws" {
  region  = "us-west-1"
}

resource "aws_security_group" "this" {
  name = "test_sg"

  egress {
    protocol = "-1"
    from_port = "0"
    to_port = "0"
  }
}

```

### Steps to Reproduce

```sh
terrafrom init && terrafrom apply -auto-approve

aws ec2 describe-security-groups --group-ids sg-0f3ac859864629452 --no-cli-pager
{
    "SecurityGroups": [
        {
            "Description": "Managed by Terraform",
            "GroupName": "test_sg",
            "IpPermissions": [],
            "OwnerId": "***",
            "GroupId": "sg-0f3ac859864629452",
            "IpPermissionsEgress": [],
            "VpcId": "***"
        }
    ]
}
```

### Important Factoids

Creating a resource in CloudFormation without specifying a list of CIDR blocks for the Egress rule returns an error.

Example config:
```yaml
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Test
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: 0
        ToPort: 0
```

Response:
```
Resource handler returned message: "Only one of CidrIp, CidrIpv6, DestinationPrefixListId or DestinationSecurityGroupId can be specified" (RequestToken: cf23d21b-5b77-50c0-6f76-df534f40d904, HandlerErrorCode: InvalidRequest)
```

### Would you like to implement a fix?

None
