### ISSUE TITLE
[Bug]: TF_AWS_DEFAULT_TAGS works in plan and fails in apply

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform-provider-aws#38829]
### Terraform Core Version

1.8.1

### AWS Provider Version

5.62.0

### Affected Resource(s)

* aws provider

### Expected Behavior

Apply works as expected without an error

### Actual Behavior

The plan shows this which is affected

```diff
  # aws_iam_role.default will be updated in-place
! resource "aws_iam_role" "default" {
!       tags_all              = {
+           "repository"             = "github.com/org/repo"
+           "repository_dir"         = "file-directory-of-terraform/"
            # (9 unchanged elements hidden)
        }
        # (11 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

The apply shows this

```
```

### Relevant Error/Panic Output Snippet

```shell
Error: Provider produced inconsistent final plan

When expanding the plan for aws_iam_role.default to include new values
learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
produced an invalid new value for .tags_all: element "repository" has
vanished.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for aws_iam_role.default to include new values
learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
produced an invalid new value for .tags_all: element "repository_dir" has
vanished.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Terraform Configuration Files

Create a simple role without setting tags or tags_all or default_tags on the aws provider

### Steps to Reproduce

1. Set the env vars
    ```bash
    export TF_AWS_DEFAULT_TAGS_repository="github.com/org/repo"
    export TF_AWS_DEFAULT_TAGS_repository_dir="file-directory-of-terraform/"
    ```
3. Run plan and save to a plan file
4. Verify the tag changes from the env var
5. Run apply on the plan file and see the failure

### Important Factoids

I saw this in an atlantis deployment with the following configuration

```yaml
workflows:
  terraform:
    plan:
      steps:
        # These env vars TF_AWS_DEFAULT_TAGS_ will work for aws provider 5.62.0+
        # https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.62.0
        - &env_default_tags_repository
          env:
            name: TF_AWS_DEFAULT_TAGS_repository
            command: 'echo "github.com/${HEAD_REPO_OWNER}/${HEAD_REPO_NAME}"'
        - &env_default_tags_repository_dir
          env:
            name: TF_AWS_DEFAULT_TAGS_repository_dir
            command: 'echo "${REPO_REL_DIR}"'
```

The workaround was to add the same env vars for both `plan` and `apply` stages which is odd because this is not needed for `TF_VAR_` inputs.

```yaml
    apply:
      steps:
        # These env vars TF_AWS_DEFAULT_TAGS_ will work for aws provider 5.62.0+
        # https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.62.0
        - *env_default_tags_repository
        - *env_default_tags_repository_dir
```

### References

* https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.62.0
* https://github.com/hashicorp/terraform-provider-aws/issues/33339

### Would you like to implement a fix?

No
