### ISSUE TITLE
[Enhancement]: Support for VPC Endpoint Service Contributor Insights

### ISSUE THREAD

**Issue by AliAllomani** [hashicorp/terraform-provider-aws#39813]
### Description

Adding support for enabling Contributor Insights for VPC Endpoint Service resource

CloudFormation example,

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html#cfn-ec2-vpcendpointservice-contributorinsightsenabled

 ```yaml
   EndpointService:
        Type: "AWS::EC2::VPCEndpointService"
        Properties:
            AcceptanceRequired: false
            ContributorInsightsEnabled: true
            NetworkLoadBalancerArns:
                - !Ref XXX
  ```

### Affected Resource(s) and/or Data Source(s)

* aws_vpc_endpoint_service

### Would you like to implement a fix?

None
