### ISSUE TITLE
[Bug]: STS Error when using Terraform in GitLab Runner

### ISSUE THREAD

**Issue by westsym** [hashicorp/terraform-provider-aws#41246]
### Terraform Core Version

1.10.5

### AWS Provider Version

5.85.0, 5.84.0

### Affected Resource(s)

I have some Terraform which provisions an EKS cluster and it has been working fine.  This development was on a local machine, Ubuntu WSL, and I have since moved the state into GitLab HTTP State Backend and running terraform plan on the local machine states no changes are required - that is expected.

However, when I run the pipeline in a GitLab Docker runner using the Ubuntu image I run into an STS error when doing a plan.

### Expected Behavior

Terraform plan runs as expected and pipeline completes. 

### Actual Behavior

I've tried different runners and some other issues that had STS problems had solutions that were DNS related so I tried setting `resolv.conf` in the container to 8.8.8.8 but still the same issue.  I have checked the credentials a number of times and I can't see any other issue.  The credentials are in GitLab CI/CD variables. 

Below is my pipeline:

```yaml
stages:
  - plan

image: ubuntu:latest  # Use Ubuntu image for the pipeline

before_script:
  # Set Terraform state file credentials
  - export TF_LOG=DEBUG
  - export TF_USERNAME="${STATE_USERNAME}"
  - export TF_PASSWORD="${STATE_PASSWORD}"
  - export TF_VAR_AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
  - export TF_VAR_AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
  - export TF_VAR_AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}"
  - apt-get update
  - apt-get install -y unzip curl lsb-release gpg
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  - apt-get update
  - apt-get install -y terraform
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install
  - aws --version
  - terraform version

plan:
  stage: plan
  script:
    - terraform init -backend-config=username=$TF_USERNAME -backend-config=password=$TF_PASSWORD
    - echo $AWS_DEFAULT_REGION
    - terraform plan -out=tfplan  # Run terraform plan and save the plan to 'tfplan'
```

I've tried spinning up an Ubuntu docker container and copying the commands into it and it does execute the `terraform plan` stage successfully.  Would appreciate some insight into what is going on.  The region I am using is `us-east-2`.

### Relevant Error/Panic Output Snippet

```shell
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: Retrieving AWS account details: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, decomposing request: net/http: invalid header field value for "Authorization"
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on providers.tf line 3, in provider "aws":
│    3: provider "aws" {
│
```

### Terraform Configuration Files

# providers.tf

provider "aws" {
  region     = var.aws_region
  access_key = var.AWS_ACCESS_KEY_ID
  secret_key = var.AWS_SECRET_ACCESS_KEY
}

# Data sources for EKS cluster access
data "aws_eks_cluster" "cluster" {
  name = aws_eks_cluster.main.name
}

data "aws_eks_cluster_auth" "cluster" {
  name = aws_eks_cluster.main.name
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}

provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority[0].data)
    token                  = data.aws_eks_cluster_auth.cluster.token
  }
}

### Steps to Reproduce

Create pipeline using a Docker runner with the Ubuntu image using latest AWS CLI, Terraform and AWS Terraform provider.

### Would you like to implement a fix?

None
