### ISSUE TITLE
[Enhancement]: Support EKS Pod Identity tokens with audience "pods.eks.amazonaws.com" for S3 backend (or alternative support via AssumeRoleForPodIdentity)

### ISSUE THREAD

**Issue by ddukbg** [hashicorp/terraform-provider-aws#41473]
### Description

Currently, the Terraform AWS Provider’s S3 backend uses the traditional  
`STS:AssumeRoleWithWebIdentity` API, which requires that the provided web identity token’s audience be `"sts.amazonaws.com"`.  
In EKS Pod Identity environments, however, the default token issued to pods may have the audience  
`"pods.eks.amazonaws.com"`.

While other applications using modern AWS SDKs (or AWS CLI v2) can leverage the EKS Pod Identity Agent  
and call `AssumeRoleForPodIdentity` (or similar internal APIs) to obtain temporary credentials,  
Terraform’s S3 backend still relies on the legacy API call and fails with an  
`InvalidIdentityToken: Incorrect token audience` error when the token audience is `"pods.eks.amazonaws.com"`.

We request an enhancement that enables the provider to support EKS Pod Identity tokens even when their  
audience is `"pods.eks.amazonaws.com"`. This could be achieved by either:

- **Automatically converting or normalizing the token audience:**  
  Add logic to change the audience from `"pods.eks.amazonaws.com"` to `"sts.amazonaws.com"`  
  before making the STS call.

- **Implementing support for the newer API:**  
  Introduce support for `AssumeRoleForPodIdentity` (or a similar API) that directly accepts  
  tokens issued by the EKS Pod Identity Agent.

**Note:**  
I acknowledge that I might be misunderstanding some of the underlying mechanisms.  
It’s possible that this issue is largely confined to the S3 backend’s authentication implementation,  
and that other AWS functionalities might already work correctly in EKS Pod Identity environments.  
However, as of now, the S3 backend is the most prominent case where this issue is observed.  
Further testing may be required to determine whether other AWS resource operations are similarly affected.

### Affected Resource(s) and/or Data Source(s)

- S3 Backend (for remote state storage)
- Potentially, any AWS provider functionality that uses assume_role_with_web_identity configuration

### Potential Terraform Configuration

```terraform
provider "aws" {
  region = "ap-northeast-2"

  assume_role_with_web_identity {
    role_arn                = "arn:aws:iam::123456:role/test-eks-cluster-atlantis-pod-id-role"
    session_name            = "example-session"
    web_identity_token_file = "/var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token"
  }
}
```

### References

- [[Amazon EKS Pod Identity Documentation](https://docs.aws.amazon.com/eks/latest/userguide/pod-identity.html)](https://docs.aws.amazon.com/eks/latest/userguide/pod-identity.html)  
- [[AWS STS AssumeRoleWithWebIdentity API Reference](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html)](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html)  
- Discussions comparing EKS Pod Identity with IRSA and the newer approaches (e.g., re:Invent 2023 announcements)

---

**Flow Diagram of the Current Issue (S3 Backend)**

```
┌─────────────────────────────────────────────┐
│      Atlantis Pod (Terraform init)          │
│ AWS Config:                                 │
│   web_identity_token_file =                │
│   /var/run/secrets/pods.eks.amazonaws.com/serviceaccount/eks-pod-identity-token   │
└─────────────────────────────────────────────┘
                  │
                  ▼
┌─────────────────────────────────────────────┐
│ Projected Token File Content (JWT)          │
│ {                                           │
│   "aud": ["pods.eks.amazonaws.com"],        │
│    ...                                      │
│ }                                           │
└─────────────────────────────────────────────┘
                  │
                  ▼
┌─────────────────────────────────────────────┐
│ Terraform S3 Backend                        │
│ (calls AWS SDK AssumeRoleWithWebIdentity)     │
└─────────────────────────────────────────────┘
                  │
                  ▼
┌─────────────────────────────────────────────┐
│       AWS STS API                           │
│   Expects token "aud": "sts.amazonaws.com"    │
│   Receives token "aud": "pods.eks.amazonaws.com"  │
│   → Returns "InvalidIdentityToken" error     │
└─────────────────────────────────────────────┘
```

---

I believe this enhancement is necessary for Terraform to fully support EKS Pod Identity environments without requiring users to modify their token audience. I would appreciate your review and consideration for adding support for either automatic token audience normalization or direct support for the new Pod Identity API (AssumeRoleForPodIdentity).

Thank you for your time and consideration!

### Would you like to implement a fix?

None

**Comment by egorksv** [comment]
Workaround for those who hit this: extract token with curl and create .aws/config in shared volume. Verified with fluxcd runner image, terraform successfully initialises S3 backend with this configuration.

```
apiVersion: v1
kind: Pod
metadata:
  name: runner
  namespace: gs-stg
  labels:
    app: awscli
spec:
  serviceAccountName: terraform-runner
  volumes:
    - name: shared-data
      emptyDir: {}

  initContainers:
    - name: init
      image: private/curl-with-jq:latest
      volumeMounts:
        - mountPath: /tmp/awscreds
          name: shared-data
      command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Running init container"
          TOKEN=$(cat $AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE)
          export CREDS=$(curl $AWS_CONTAINER_CREDENTIALS_FULL_URI --header "Authorization: $TOKEN")
          ACCESS_KEY_ID=$(echo $CREDS | jq -r '.AccessKeyId')
          SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.SecretAccessKey')
          SESSION_TOKEN=$(echo $CREDS | jq -r '.Token')
          cat << EOF > /tmp/awscreds/config
          [default]
          aws_access_key_id = $ACCESS_KEY_ID
          aws_secret_access_key = $SECRET_ACCESS_KEY
          aws_session_token = $SESSION_TOKEN
          EOF
          

  containers:
  - name: runner
    image: ghcr.io/flux-iac/tf-runner:v0.16.0-rc.5
    volumeMounts:
      - mountPath: /home/runner/.aws
        name: shared-data
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    env:
    - name: AWS_DEFAULT_REGION
      value: "us-east-1"
```
