### ISSUE TITLE
Error: No valid credential sources found in GitHub Action after aws-actions/configure-aws-credentials@v4.1.0

### ISSUE THREAD

**Issue by RyanMartin-Carewell** [hashicorp/terraform-provider-aws#42420]
### Terraform and AWS Provider Version

```console
Terraform v1.11.4
+ provider registry.terraform.io/hashicorp/aws v5.95.0
```

### Expected Behavior

`terraform plan` and `terraform apply` access AWS credentials from environment and access my account via the provided role

### Actual Behavior

`Error: No valid credential sources found`

The (redacted) environment vars are not picked up by the TF AWS provider
AWS_REGION=us-east-1
AWS_SECRET_ACCESS_KEY=***
AWS_ACCESS_KEY_ID=***
AWS_SESSION_TOKEN=***

### Relevant Error/Panic Output

```console
Waiting for the plan to start...
Terraform v1.11.4
on linux_amd64
Initializing plugins and modules...
╷
│ Error: No valid credential sources found
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 1, in provider "aws":
│    1: provider "aws" {}
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: failed to refresh cached credentials, no EC2 IMDS role found,
│ operation error ec2imds: GetMetadata, request canceled, context deadline
│ exceeded
│
╵
Operation failed: failed running terraform plan (exit 1)
```

### Sample Terraform Configuration

<details>
<summary>Click to expand configuration</summary>

```hcl
provider "aws" {}

terraform {
  cloud {
    organization = "<our-hcl-tf-org>"
    workspaces {
      name = "<our-workspace>"
    }
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.95.0"
    }
  }
}
```

```yaml
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ inputs.region }}
          role-to-assume: ${{ inputs.role }}
          role-session-name: 'GitHubActions-${{ github.run_id }}'

      - name: Get AWS Caller Identity
        run: |
          aws sts get-caller-identity

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.4"
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Terraform Init
        id: init
        run: |
          cd ./infra/terraform
          terraform init -input=false -no-color

      - name: Terraform Plan
        id: plan
        run: |
          cd ./infra/terraform
          terraform plan -out=tfplan -no-color -input=false
```

</details>

### Steps to Reproduce

1. Create a simple AWS TF config with an unconfigured provider - `provider "aws" {}` using a recent hashicorp.aws v5 (in our case v5.95)
2. Wrap it in a GitHub Action with a prior step `uses: aws-actions/configure-aws-credentials@v4.1.0` to perform the AWS AssumeRoleWithWebIdentity call
3. Verify that AWS_* env vars are correctly set via `aws sts get-caller-identity`
4. Configure terraform with `uses: hashicorp/setup-terraform@v3`
5. Step run: `terraform init -input=false -no-color`
6. Step run: `terraform plan -out=tfplan -no-color -input=false`

### Debug Logging

<details>
<summary>Click to expand log output</summary>

```console
Run aws sts get-caller-identity
{
    "UserId": "[REDACTED]:GitHubActions-[REDACTED]",
    "Account": "[REDACTED]",
    "Arn": "arn:aws:sts::[REDACTED]:assumed-role/GitHubActionDeploy/GitHubActions-[REDACTED]"
}
```

```console
2025-04-29T19:47:28.427Z [INFO]  Terraform version: 1.11.4
2025-04-29T19:47:28.427Z [INFO]  Go runtime version: go1.23.3
2025-04-29T19:47:28.427Z [INFO]  CLI args: []string{"/home/runner/work/_temp/6f5cdc13-6efc-4684-a19b-6bd54995e3fc/terraform-bin", "plan", "-out=tfplan", "-no-color", "-input=false"}
2025-04-29T19:47:28.427Z [INFO]  Loading CLI configuration from /home/runner/.terraformrc
2025-04-29T19:47:29.255Z [INFO]  cloud: starting Plan operation
Running plan in HCP Terraform. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.
Preparing the remote plan...
To view this run in a browser, visit:
[REDACTED]
Waiting for the plan to start...
Terraform v1.11.4
on linux_amd64
Initializing plugins and modules...
╷
│ Error: No valid credential sources found
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 1, in provider "aws":
│    1: provider "aws" {}
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: failed to refresh cached credentials, no EC2 IMDS role found,
│ operation error ec2imds: GetMetadata, request canceled, context deadline
│ exceeded
│
╵
Operation failed: failed running terraform plan (exit 1)
─────────────────────────────────────────────────────────────────────────────
Saved the plan to: tfplan
To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"
```

</details>

### GenAI / LLM Assisted Development

n/a

### Important Facts and References

Your documentation claims that an empty `provider "aws" {}` config will cause it to use the environment vars for credentials. This is not taking place.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs#environment-variables

### Would you like to implement a fix?

No
