### ISSUE TITLE
Rename an existing Resource causes it to be deleted and not replaced

### ISSUE THREAD

**Issue by hashibot** [hashicorp/terraform-provider-aws#433]
_This issue was originally opened by @philltomlinson as hashicorp/terraform#10792. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.8.1

### Affected Resource(s)
Please list the resources as a list, for example:
- AWS_CLOUDWATCH_METRIC_ALARM

However this may well effect multiple resources as the issue is with the resource rename.

### Terraform Configuration Files
```hcl
resource "aws_cloudwatch_metric_alarm" "ReportingServices_Redshift_Disk_Space" {
  alarm_name = "ReportingServices_Redshift_Disk_Space"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods = "5"
  metric_name = "PercentageDiskSpaceUsed"
  dimensions {
    ClusterIdentifier = "redshift.cluster.id"
  }
  namespace = "AWS/Redshift"
  period = "300"
  statistic = "Average"
  threshold = "75"
  alarm_description = "This metric monitors disk utilisation of redshift cluster"
  insufficient_data_actions = []
}
```

### Expected Behavior
I first deploy the resource everything works. I then change the name of the resource to:
```hcl
resource "aws_cloudwatch_metric_alarm" "ReportingServices_Redshift2_Disk_Space" {
```
I would expect terraform to re-create the resource.

### Actual Behavior
It deletes the resource but does not replace it. Therefore the alarm disappears.

### Steps to Reproduce
1. `terraform apply`

**Comment by philippmoehler0440** [comment]
Hi,

yesterday we had a large issue caused by the following resource:

```tf
resource "aws_s3_bucket_object" "name_new" { // original name veiled
  bucket       = "${aws_s3_bucket.web.bucket}"
  key          = "our.file"
  content      = "${data.template_file.XXX.rendered}"
  content_type = XXX
  etag         = "${md5(data.template_file.XXX.rendered)}"

  cache_control = XXX
}
```

What we did was _only_ a renaming of this resource without changing any attributes within.
Terraform `plan` said (first for our nonlive environment):

```
  + module.static.aws_s3_bucket_object.name_new  // original name veiled
      id: <computed>
      acl: XXX
      bucket: 
      cache_control:  XXX
      content: XXX
      content_type: XXX
      etag: XXX
      key:  XXX
      server_side_encryption:  <computed>
      storage_class:  <computed>
      version_id:  <computed>

  - module.static.aws_s3_bucket_object.name_old  // original name veiled
```

and then within the `apply` step (originally this order):

```
...
module.static.aws_s3_bucket_object.name_old: Destruction complete after 0s
...
module.static.aws_s3_bucket_object.name_new: Creation complete after 1s
...
```
The file existed afterwards (like expected) on our S3 Bucket.
Then our live deployment did the same steps with matching plan and apply output.

But: the target file was overwritten on our Bucket and afterwards deleted. (and no, we do not upload
our needed Files to S3 with the use of terraform - this is only for a single file and case ;) )

Version: Terraform v0.11.7

Is there any way to prevent this case or is it the normal terraform behaviour because you can not know that it is the same target file on S3?
